### ISSUE TITLE
Process crashes when Stream.Dispose throws an exception

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#1084]
### Discussed in https://github.com/microsoft/vs-streamjsonrpc/discussions/1083

<div type='discussions-op-text'>

<sup>Originally posted by **lostmsu** October  1, 2024</sup>
I use `JsonRpc` over custom network-based `DataChannelStream`, wrapped in `BrotliStream` for compression. I use the simplified `JsonRpc.Attach<T>(stream)` to obtain the wrapper for the remote service.

The problem is when connection drops (I'm not quite sure for the reason, but it is not important right now), the whole app crashes due to (as far as I understand it) unobserved exception in a worker thread. Here's the stack trace:

> `System.AggregateException`: One or more errors occurred. (Data channel is closed)
>  --->` System.IO.IOException`: Data channel is closed
> `DataChannelStream.Write(ReadOnlySpan1 buffer)` in DataChannelStream.cs:line 248
>    --- End of inner exception stack trace ---
>    at `DataChannelStream.Write(ReadOnlySpan buffer)` in DataChannelStream.cs:line 250
>    at `System.IO.Compression.BrotliStream.WriteCore(ReadOnlySpan buffer, Boolean isFinalBlock)`
>    at System.IO.Compression.BrotliStream.Dispose(Boolean disposing)
>    at System.IO.Stream.Close()
>    at Nerdbank.Streams.FullDuplexStream.CombinedStream.Dispose(Boolean disposing)
>    at System.IO.Stream.Close()
>    at StreamJsonRpc.PipeMessageHandler.<>c.<.ctor>b__4_0(Exception ex, Object state)
>    at System.IO.Pipelines.PipeCompletionCallbacks.Execute(PipeCompletionCallback callback, List& exceptions)
>    --- End of inner exception stack trace ---
>    at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
>    at System.IO.Pipelines.Pipe.<>c.<.cctor>b__100_2(Object state)
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

Is creating `JsonRpc` instance explicitly and awaiting its `Completion` my only option here?

P.S. Here `FullDuplexStream` is used because `BrotliStream` is not full-duplex (e.g. I have to create one for receiving + decompression and another for compression + sending)
P.P.S. `StreamJsonRpc` v2.19.27</div>

We should probably catch and swallow exceptions thrown from these Dispose methods.

**Comment by lostmsu** [comment]
@AArnott I just upgraded to 2.20.17 and hit the same issue with the following stack:


 ```
 at Borg.Conduit.DataChannelStream.Send(ReadOnlySpan`1 buffer) in DataChannelStream.cs:line 240
   at Borg.Conduit.DataChannelStream.Write(ReadOnlySpan`1 buffer) in DataChannelStream.cs:line 259
   at System.IO.Compression.BrotliStream.WriteCore(ReadOnlySpan`1 buffer, Boolean isFinalBlock)
   at System.IO.Compression.BrotliStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Nerdbank.Streams.FullDuplexStream.CombinedStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at StreamJsonRpc.PipeMessageHandler.<>c.<.ctor>b__4_0(Exception ex, Object state)
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute(PipeCompletionCallback callback, List`1& exceptions)
   --- End of inner exception stack trace ---
   at System.IO.Pipelines.PipeCompletionCallbacks.Execute()
   at System.IO.Pipelines.Pipe.<>c.<.cctor>b__100_2(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

This happened after I did some calls over RPC, then called `JsonRpc.Dispose`

**Comment by lostmsu** [comment]
NVM, I realized this fix has not been released yet.

**Comment by ryannewington** [comment]
Sorry to be a pain @AArnott but do you have an ETA on a release of v2.21? We're hitting this issue with a customer at the moment

**Comment by lostmsu** [comment]
@ryannewington https://gist.github.com/lostmsu/e3fb9fe2c4cc3eed6c11fdab0a167cd4

**Comment by ryannewington** [comment]
@lostmsu thank you so much! Didn't even think of this!

**Comment by AArnott** [comment]
v2.21 will release at the same time as Visual Studio 17.13. I'm glad you have a workaround for now.
