### ISSUE TITLE
Allow for custom message routing/handling

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#111]
## Requirements
1. A specially initialized `JsonRpc` object may send messages that are routed in a non-standard way. For example, sent messages may be routed to different recipients depending on the method name.
1. A specialized router that receives and forwards JSON-RPC messages to various destinations, possibly changing their contents along the way. One destination may be a "local" `JsonRpc` instance.

### Rough notes from earlier:
1. ✔️  Revise `DelimitedMessageHandler` contract to convert between `JObject` and the transport (consider #80) instead of a single string containing the entire message.
1. ✔️ Allow for a plugin serializer to convert between `JToken` and `byte[]` (on the stream). The idea being to support a binary serialization later on as an option. ❓ But web sockets probably would prefer to remain encoded as text rather than as binary, so how would that work? Perhaps we don't know whether it's a string or `byte[]` on the transport side. We just give and receive `JToken` objects with this plugin and it serializes it to the transport however it wants? But that couples the serializer to the transport. 👎 
1. ❌ Allow 'middleware' to intercept `JObject` being written or read and choose to transform it, or redirect it.
1. ✔️ Alternative to intercepting/passing around JObject would be to let our own strongly typed JSON-RPC classes (`JsonRpcMessage`, `JsonRpcError`, etc.) be the medium of exchange.

**Comment by DustinCampbell** [comment]
I'm interested in this too. Currently, it's pretty difficult to extract the `id` of a `JsonRpcMessage`, which is needed for tracking requests and handling the [`$/cancelRequest` notification](https://microsoft.github.io/language-server-protocol/specification#cancelRequest) from LSP.

**Comment by AArnott** [comment]
@DustinCampbell StreamJsonRpc has built-in support for cancellation the way you mention and automatically associates responses with their requests. Why do you need the `id` of the `JsonRpcMessage`?

Or is it that you're code is an intermediary (and thus you're commenting on a routing issue)?

**Comment by DustinCampbell** [comment]
I know that there's support for dispatching to methods with a `CancellationToken`. However, it was unclear to me how that would work if the client sends a notification to the server to request cancellation of a previous request. That's a scenario supported by LSP.

**Comment by AArnott** [comment]
Yes, when StreamJsonRpc dispatches to a method that accepts `CancellationToken`, it wires it up such that when an LSP-style cancellation notification comes in, StreamJsonRpc will automatically cancel the token.
And the corollary is also true: when using StreamJsonRpc on the client side and supplying a CancellationToken, that is wired up by the library such that if the token is canceled before the response comes back, an LSP-style cancellation notification is transmitted.
So altogether, just use CancellationTokens and it all Just Works. 😄

**Comment by DustinCampbell** [comment]
Ah-ha! I just found this: https://github.com/Microsoft/vs-streamjsonrpc/blob/6972f058360aade5ed47a7e0d6b417ff0cabf910/src/StreamJsonRpc/JsonRpc.cs#L1355.

Great!
