### ISSUE TITLE
What WebSocket library is suggested to integrate with vs-streamjsonrpc

### ISSUE THREAD

**Issue by yingfangdu** [Microsoft/vs-streamjsonrpc#112]
I am trying to look a mature WebSocket library to use with vs-streamjsonrpc. There are a couple of choices search from GitHub and I noticed that some implementation is not thread thread. 

So it will be an issue when integrate with vs-streamjosnrpc as this library is non-blocking to accept RPC calls and can reply responses in different threads.

Is there any suggestion about which WebSocket library to use?

Thanks very much.

**Comment by AArnott** [comment]
This library's support for web sockets are based on `System.Net.WebSockets.WebSocket`, which is part of .NET Framework / .NET Standard. No need for a 3rd party library. Does that help?

**Comment by yingfangdu** [comment]
thanks, System.Net implementation for Windows while there is missing implementation for Xamarin.Mac. So that we cannot use it.

While there are other existing third party libraries while their WebSocket implementation does not inherit from System.Net.WebSocket so that it cannot work with vs-streamjsonrpc. for example: websocket-sharp, fleck, supersocket.

The last one tried was Ninja.WebSockets while it is not thread safe. Maybe we should adopt this and fix the existing issues.

anyway, thanks very much for your help.

**Comment by AArnott** [comment]
I see. StreamJsonRpc should be able to work with any web socket library, but an adapter like our [`WebSocketMessageHandler`](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/WebSocketMessageHandler.cs) will need to be written for it.

**Comment by yingfangdu** [comment]
I was wrong here that vs-streamjsonrpc has thread access protection to access the websocket.

See DelimitedMessagehandler's ReadAsync and WriteAsyn, it uses semaphore to protect the message's integrity. 

So it is fine for me to use ninja.Websockets
