### ISSUE TITLE
How to format outbound messages without whitespace between tokens?

### ISSUE THREAD

**Issue by MikhailNatalenko** [Microsoft/vs-streamjsonrpc#113]
Hi, how can i get reed from `\r\n` in JSON messages? I forced to use parser, that can not parce JSON RPC message correctly with `\r\n`.

**Comment by AArnott** [comment]
Interesting requirement. I'd say "get a real JSON parser" (since the official [json spec](https://json.org/) explicitly allows for whitesepace:

> Whitespace can be inserted between any pair of tokens. Excepting a few encoding details, that completely describes the language.

...but you say you're forced to use a particular parser. I'm looking into whether this is possible today.
