### ISSUE TITLE
Log interface needed in vs-streamjsonrpc

### ISSUE THREAD

**Issue by yingfangdu** [Microsoft/vs-streamjsonrpc#115]
Ideally I think JsonRpc should provide some way to let caller to add logging/tracing (error, info).

In my example, when JsonRpc Server has some error executing some RPC call, it will only transmit the exception back to the client while Server does not know what error happens at all. It would be great to provide a way to let Server to log these errors or info.

Today, it is more popular to add telemetry and tracing to identify issues and bugs. It would be great to have such functionalities.

**Comment by jasongin** [comment]
Live Share uses `System.Diagnostics.TraceSource` and related classes extensively. For RPC, we actually have a distinctly-named `TraceSource` instance for each RPC service name (prefix). That enables us to set up different filtering levels for different components by using tracing filters that check the source name. For example some components have relatively "chatty" RPC messages so we'd only trace errors & warnings by default, while for other components it's helpful to trace all RPC messages. I don't know how that would map to StreamJsonRpc where the "prefix" is a less-formalized construct.

As in the OP's example, any exception thrown by an RPC server's handler callback would be traced (at error tracing level) in addition to being returned to the client as a JSON-RPC error response. But in addition we simply trace every JSON-RPC message (at a verbose tracing level) on both ends of the channel, which can be really helpful during development. (We can configure tracing differently for development vs production environments, partly for privacy reasons. But that's handled in the filter / listener side of the tracing.)

As for meeting Live Share's requirements, it doesn't necessarily have to be based on `TraceSource`. We could adapt any callback as long as it includes the (non-serialized) RPC message.

**Comment by yingfangdu** [comment]
I have a question here, when you mention this, where the error message is stored in the server side? now we use Aria to store telemetry data and error tracings. So I hope application can inject its own log implementation. 

> an RPC server's handler callback would be traced (at error tracing level) in addition to being returned to the client as a JSON-RPC error response

**Comment by AArnott** [comment]
I'm working on this now.
