### ISSUE TITLE
May I compile it in .NET4?

### ISSUE THREAD

**Issue by DMKun** [Microsoft/vs-streamjsonrpc#122]
My App may be used in the Window XP. But Window XP support the last .NET version is .NET4. How can I complie vs-streamjsonrpc in .NET4? I need to remove the context Header, and build it for Windows XP.

**Comment by AArnott** [comment]
I just took a quick look and I'm afraid we have a lot of dependencies that are only available on .NET 4.5. Getting this to compile on net40 would be a significant undertaking that we don't have time for. It's open source, and you're welcome to do the port yourself. But we can't fund this.

Have you considered .NET Core on Windows XP? (I'm not sure if that's an option).

**Comment by AArnott** [comment]
It looks like .NET Core requires [at least Windows 7 SP1](https://docs.microsoft.com/en-us/dotnet/core/windows-prerequisites?tabs=netcore2x).
