### ISSUE TITLE
Add support for compact binary serialization

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-streamjsonrpc#124]
BSON is binary serialization version of JSON. We can use the BsonWriter from [this package](https://www.nuget.org/packages/newtonsoft.json.bson) to possibly get performance wins.

Also consider MessagePack, if indeed it can be a drop-in replacement (via the newtonsoft.json JsonWriter/JsonReader plugin mechanism) and is truly better as [claimed](https://stackoverflow.com/questions/6355497/performant-entity-serialization-bson-vs-messagepack-vs-json/6357042#6357042) by its author. [More info about MessagePack](https://github.com/neuecc/MessagePack-CSharp).

Also consider [gRPC](https://grpc.io/).

Let's measure it and add it if it's significant.

**Comment by peterwald** [comment]
Consider [Bond](https://microsoft.github.io/bond/) over [GRPC](https://microsoft.github.io/bond/manual/bond_over_grpc.html).

**Comment by AArnott** [comment]
I tried out [MessagePack for C#](https://github.com/neuecc/MessagePack-CSharp). It took ~1 second to transmit 200K records, and 63MB of transmitted data.

Using newtonsoft.json to serialize took 14-23 seconds for the same data, and undoubtedly _much_ more bytes of transmitted data, although I did not measure it.

**Comment by AArnott** [comment]
The above measurement was when using integer-keyed properties. When using it in "newtonsoft compability mode", it took on average 1.4 seconds and 88 MB of transmission bytes.

**Comment by AArnott** [comment]
I found some reports that BSON serialization is marginally faster (and sometimes slower) than JSON.
