### ISSUE TITLE
Creating a JsonRPC on top of a SSH.Net ShellStream

### ISSUE THREAD

**Issue by hippiehunter** [Microsoft/vs-streamjsonrpc#197]
ShellStream extends System.IO.Stream so im passing it into JsonRPC.Attach and I'm getting the following trace after I try to call my first method.
```
Client Information: 3 : Listening started.
Client Information: 8 : { ... }
Client Verbose: 8 : Sent: { ... }
Client Information: 13 : Connection closing (RemotePartyTerminated: Reached end of stream.). 
Exception thrown: 'System.InvalidOperationException' in System.IO.Pipelines.dll
Writing is not allowed after writer was completed.
```
As far as the ShellStream is concerned, we have not terminated anything and nothing has been disposed. Any suggestions or a direction to pursue?

**Comment by AArnott** [comment]
This happens when reading from the stream returns 0 bytes, which signifies the end of a stream. Could the ShellStream be returning 0 bytes from ReadAsync?

**Comment by hippiehunter** [comment]
Thanks that was the issue, If anyone ends up looking around with a similar issue, I solved it by wrapping the ShellStream in my own implementation that uses the data received events and a TaskCompletionSource<int> to implement ReadAsync directly rather than relying on the System.IO.Stream implementation.

**Comment by hippiehunter** [comment]
ShellStream is just stdin/stdout for the remote SSH session. Its a little bit janky setting up the initial connection and getting to a settled state where your target process is running but once that's done I've had pretty good success.

I have a somewhat burning desire to fork SSH.Net and re-implement it on top of Pipelines but that won't fit in my current timeline.
