### ISSUE TITLE
MsgPack and in non beta?

### ISSUE THREAD

**Issue by seertenedos** [Microsoft/vs-streamjsonrpc#198]
Is msgpack only supported in the beta? if it is supported in the release version is there an example anywhere? If it is only in the beta is there any idea when there will be a non beta version with msgpack support?

**Comment by AArnott** [comment]
Alternative formatter support is new in 2.0, which is still in beta. MessagePack won't be in box, but as the tests show, is easy to add yourself using the extensibility point and even the test source code itself.
I expect we'll have a stable release in a month, but it depends on how much usage the beta gets. We want folks to try it out and let us know it works for them.
