### ISSUE TITLE
Add support for 1.0 version of JSON-RPC

### ISSUE THREAD

**Issue by Kikimora** [Microsoft/vs-streamjsonrpc#220]
I'm getting JSON responses from bitcoind like this
```json
{
  "result": null,
  "error": {
    "code": -1,
    "message": "JSON value is not a string as expected"
  },
  "id": 2
}
```

Same happens with result, I see response where "result" != null and "error" == null.

Unfortunately JsonMessageFormatter prioritise ["result"](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/JsonMessageFormatter.cs#L116) over "error" and parse such response as if it has result. It should throw exception instead.

**Comment by AArnott** [comment]
Interesting. Apparently bitcoind has implemented JSON-RPC 1.0 [which allows such responses](https://www.jsonrpc.org/specification_v1#a1.2Response), whereas this library is designed for JSON-RPC 2.0 [which disallows such responses](https://www.jsonrpc.org/specification#response_object).

We certainly could add support for JSON-RPC 1.0 to this library. I'll keep this issue to track that.

**Comment by Kikimora** [comment]
Suggested fix for JsonMessageFormatter
```csharp
        public static bool HasValue(this JToken token)
        {
            if (token == null) return false;
            switch (token)
            {
                case JContainer container: return container.HasValues;
                case JValue value: return value.Value != null;
                default: throw new ArgumentException("Unsupported token type");
            }
        }

        public JsonRpcMessage Deserialize(JToken json)
        {
            try
            {
                return
                        json["method"].HasValue() ? ReadRequest(json) :
                        json["error"].HasValue()  ? (JsonRpcMessage)ReadError(json) :
                        json["result"].HasValue() ? ReadResult(json) :
                        throw new JsonSerializationException("Unrecognized JSON-RPC message: " + json);
            }
            catch (JsonException exception)
            {
                var serializationException = new JsonSerializationException($"Unable to deserialize {nameof(JsonRpcMessage)}.", exception);
                serializationException.Data[ExceptionDataKey] = json;
                throw serializationException;
            }
        }
```

**Comment by AArnott** [comment]
What you propose I imagine would allow this particular case to work. But I'd be more interested in building in proper recognition of 1.0 vs. 2.0 messages, and then taking code paths based on that to enforce that the messages are valid within their spec version. For example, the response message you're getting is invalid in 2.0 and we should reject it (and drop the connection). We don't do that today, but when we recognize 1.0 messages, we can properly support them, and also actively reject such a message that claims to be a 2.0 message when it doesn't conform to the spec.

**Comment by Kikimora** [comment]
Make sense, proper support for 1.0 is way better than this hack :)
