### ISSUE TITLE
Add support for dynamic proxies with non-public interfaces

### ISSUE THREAD

**Issue by LiangJy123** [microsoft/vs-streamjsonrpc#236]
Hi~

I got a exception that "Attempting to implement an inaccessible interface"
when running this line:
``` C#
       var RpcClient = JsonRpc.Attach<IRPCFuntions>(stream);

``` 
the IRPCFuntions is defined as follows
``` C#
         interface IRPCFuntions
        {
             Task<int> SumOfAsync(int a, int b);
             Task<int> DifferenceAsync(int a, int b);
        }
```

I spent half a day but didn't find what caused the exception, can you help me ?

**Comment by AArnott** [comment]
Make the interface `public`.

This is something we could enhance to remove the requirement though, so I'll keep the issue active.

**Comment by LiangJy123** [comment]
Thank you very much! 
 I used to try to add "public" but  the "IRPCFuntions" was defined in the class ,so it didn't work.
 After got your tips, I try to define them out of the class and add "public" ,  it runs successfully.
![image](https://user-images.githubusercontent.com/13048899/52608488-236fd280-2eb5-11e9-881d-6c7062b130f7.png)

**Comment by AArnott** [comment]
Reopening to track ability to implement internal interfaces.

**Comment by AArnott** [comment]
[vs-mef does this already](https://github.com/Microsoft/vs-mef/blob/abf21ae4a0adb32b7b1a548efd83da0794ead95f/src/Microsoft.VisualStudio.Composition/Configuration/MetadataViewGenerator.cs#L110-L114) (with 95% feature complete).
We should try to consolidate the implementation into a reusable package so that this can be shared between vs-mef, vs-streamjsonrpc and even messagepack.

**Comment by AArnott** [comment]
messagepack issue tracking it: https://github.com/neuecc/MessagePack-CSharp/issues/88

**Comment by peterwald** [comment]
+1 for this feature, to support implementing an RPC protocol without publicly exposing all of the interfaces/types involved.

**Comment by AArnott** [comment]
@peterwald: giving a thumbs up on the issue description is a great way to accumulate votes.
