### ISSUE TITLE
InvalidOperationException on null result for InvokeAsync<int?>

### ISSUE THREAD

**Issue by miguep** [Microsoft/vs-streamjsonrpc#237]
Modifying the Sample Client and Server to use the latest version, and to return int? rather than int, with the server returning null, results in an InvalidOperationException on the client side.

seems like the problem is:

https://github.com/Microsoft/vs-streamjsonrpc/blob/0bf2419fb161b5b55bbc62e43a57419c0a93708d/src/StreamJsonRpc/JsonMessageFormatter.cs#L465

but int? is a value type, yet null is assignable to this type.

perhaps it should be:
`Verify.Operation(!typeof(T).GetTypeInfo().IsValueType && Nullable.GetUnderlyingType(typeof(T)) != null, "null result is not assignable to a value type.");`

**Comment by AArnott** [comment]
I can repro this problem. I've written a test to ensure that nullable parameters and return types work (which fails at the moment).
