### ISSUE TITLE
.NET Framework, conflicts with System.Buffers

### ISSUE THREAD

**Issue by miguep** [Microsoft/vs-streamjsonrpc#238]
The .NET Framework version of vs-streamjsonrpc runs into issues loading System.Buffers. 

This seems to be caused by System.IO.Pipelines and Nerdbank.Streams referencing different versions of System.Buffers.

Pipelines references System.Buffers version 4.4.0 , the assembly version for System.Buffers is 4.0.2
Nerdbank.Streams references System.Buffers version 4.5.0 , the assembly version for System.Buffers is 4.0.3

The output folder 46 contains System.Buffers manifested as version 4.0.3, upon use of the library the application encounters a FileLoadException "The located assembly's manifest definition does not match the assembly reference"

**Comment by AArnott** [comment]
This is likely related to https://github.com/dotnet/sdk/issues/2547

**Comment by AArnott** [comment]
@miguep Yes, there is a mix of assembly versions in the references throughout the transitive closure of dependencies. This is not abnormal though. Per the bug I linked to above, there *was* a bug where the appropriate binding redirects were not being generated during the build to make sure that the app would succeed at runtime, but that has been fixed. 

I just confirmed that when I build this project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net46</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StreamJsonrpc" Version="2.0.146" />
  </ItemGroup>

</Project>
```

It produces this .exe.config file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

Which allows the app to run. Is your build producing this .exe.config file and putting it in the bin folder next to the .exe? If not, you might try adding one or both of these properties to your project file:

```xml
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```
