### ISSUE TITLE
ONe more identical menu named External

### ISSUE THREAD

**Issue by KristinXieXie** [Microsoft/vs-streamjsonrpc#241]
When start LUT, there is one more identical menu named External. Is this a test bug? 
 And totally 379 test cases? Right?

**Comment by KristinXieXie** [comment]
![image](https://user-images.githubusercontent.com/47766663/53074021-a2ec4a00-3524-11e9-8f09-dff21348d981.png)

**Comment by AArnott** [comment]
StreamJsonRpc tests run on several platforms:

https://github.com/Microsoft/vs-streamjsonrpc/blob/9e1e77f0f95fd9bc4d8fb276741f748b0a3ebdac/src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj#L3

Test Explorer typically only runs tests on the first platform in this list. But when LUT is turned on, more platforms are executed. It's inconsistent, and Test Explorer isn't great at representing this. "External" is (just one way) how it can manifest the tests that are run that Test Explorer wouldn't normally run. It's a bit goofy, IMO. But there's nothing this library can do about it.

Please do feel free to use "Report a Problem" to file or vote on an issue regarding this. I know the LUT/Test Explorer team are open to feedback on this.
