### ISSUE TITLE
Server should create a "FooAsync" alias for method "Foo"

### ISSUE THREAD

**Issue by bsagal** [microsoft/vs-streamjsonrpc#262]
On the server i have the following method
```c#
public class Server {
    public bool Ping() => true;
}
```

On the client i have an i the following interface:

```c#
public interface IClient {
    Task<bool> PingAsync();
}
```

When using attach to create a dynamic proxy, the client is unable to call the server as the server does not have a `PingAsync` method.

If i were to have a `PingAsync` method on the server i would get an alias for a `Ping` method but this way there is no alias.

From my understanding of conversions the server method should not have and `Async` sufiix as it is a sync method but on the client i need the   `Async` suffix as it is an async method.

What is the suggested fix?

**Comment by AArnott** [comment]
Great question. Our recommended pattern is to implement the same interface on the server as on the client, which would force your server method to be async, like this:

```cs
public class Server : IClient {
    public Task<bool> PingAsync() => Task.FromResult(true);
}
```

Nevertheless I agree the server could create an alias for the method that *adds* an "Async" suffix when none exists. I'll keep the issue active to track that.

**Comment by AArnott** [comment]
I'm looking for justification to keep this issue active rather than close as Won't Fix. 

Can you tell me why you wouldn't implement `IClient` on the `Server` class as part of ensuring your API matches the server?

**Comment by bsagal** [comment]
The server implantation is based on the previous WCF contract and I am not quite ready to convert it all to async.

**Comment by AArnott** [comment]
Thanks. Are you aware you can rename it yourself with this?

```cs
public class Server {
    [JsonRpcMethod("PingAsync")]
    public bool Ping() => true;
}
```

**Comment by AArnott** [comment]
Closing due to a workaround being available or lack of popular demand. This allows us to better focus on high impact issues. If you feel this is blocking you, you may add a comment here to explain why this should be prioritized.

Thank you for your understanding.
