### ISSUE TITLE
ConnectionLostException should not be thrown when request is already canceled

### ISSUE THREAD

**Issue by richardstanton** [Microsoft/vs-streamjsonrpc#265]
I believe the intent of the ConnectionLostException is to occur when there was an unexpected error from the connection or server. However, if the client has canceled the request or disposed, then it was requested by the client and should be reported as a cancelation.
In VisualStudio several components run into a situation when closing or when aborting a background process that gets the exception unexpectedly. These code paths expect cancelation and go into an error state when they get the exception.

**Comment by AArnott** [comment]
This is related to #84 which explicitly requested something other than `OperationCanceledException` to be thrown when the remote side drops the connection on a pending request.

**Comment by AArnott** [comment]
> However, if the client has canceled the request or disposed, then it was requested by the client and should be reported as a cancelation.

I don't (yet) agree on the point that disposing the `JsonRpc` object should cause pending requests to throw OCE. IMO they should throw `ObjectDisposedException`.
