### ISSUE TITLE
Add strongly typed message support

### ISSUE THREAD

**Issue by ZoeyR** [microsoft/vs-streamjsonrpc#290]
The `vscode-jsonrpc` library has a concept of strongly typed messages, where instead of passing a string for the method you pass an object which has the parameter and return types encoded in generic parameters (e.g. `RequestType<number, string>`). Adding a similar concept to this library would enable stronger guarantees that the wrong data wasn't being passed into a method.

**Comment by AArnott** [comment]
How is this better than what we already have in dynamically generated client proxies?

**Comment by AArnott** [comment]
Closing due to non-response.
I think what vscode-jsonrpc is a reasonable attempt at strong-type programming in TypeScript. But in C# we can do much better, and I believe our [dynamic proxy support](../blob/master/doc/dynamicproxy.md) does just that.
