### ISSUE TITLE
Source information missing from PDB

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#297]
When debugging the 2.1-alpha release from external to this repo, the debugger was unable to find source code for the library, despite SourceLink being enabled.

**Comment by AArnott** [comment]
not repro in isolation

**Comment by sharwell** [comment]
As best I can tell, the problem here stems from the use of the Microsoft symbol server. The symbols downloaded from that server do not contain the SourceLink information. Since the original PDB files in the snupkg are portable PDBs but the Microsoft symbol server provides full PDBs, is it possible that the conversion operation is dropping the source information?

**Comment by sharwell** [comment]
I was able to debug with source information _only_ after manually copying the PDB from:

streamjsonrpc.2.2.34.snupkg\\lib\\netcoreapp2.1\\StreamJsonRpc.pdb

to:

C:\\symbols\\StreamJsonRpc.pdb\\E6581EA56B8F4782B1F8A6017D671DB11\\StreamJsonRpc.pdb

**Comment by AArnott** [comment]
We archive the full pdb to Microsoft symbol servers, but I don't know if these are public. We also upload portable PDBs to nuget servers so if you have that selected and with higher priority than Microsoft Public maybe you'll see it work?

**Comment by sharwell** [comment]
@AArnott the test above was performed using the public Microsoft symbol server. I was not able to find a way to adjust the relative priority of the Microsoft symbol server and the NuGet symbol server, so the _only_ way to debug this package currently is to manually download the symbols and place them in a local cache.

**Comment by AArnott** [comment]
Ah, I guess it was working for me because I don't have the "Microsoft Symbol Servers" option selected, so NuGet.org is the most preferred source. So that's an easier option for you, unless you need the _public_ Microsoft symbol server source as well.

I don't know a way to make this work better. If you are aware of one, I'm happy to consider it.
