### ISSUE TITLE
Add a system.text.json formatter

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#305]
The [new `System.Text.Json` APIs](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-apis/) are much faster than Newtonsoft.Json, and thus offer a huge perf boost without sacrificing interop as a move to MessagePack has.

Be sure when doing so to implement full streaming support such that we don't buffer an entire message before beginning deserialization.

**Comment by AArnott** [comment]
No demand for this, so closing.

**Comment by watfordgnf** [comment]
I realize this is resurrecting an old closed issue, but we would be interested in a System.Text.Json version.

We've got a job scheduler that has coordinators on nodes managing dozens of sub-processes, talking over anonymous pipes with StreamJsonRpc. The `JsonArrayPool` class causes rather large char arrays to be pinned when we ship logs back and forth. We've temporarily removed log shipping over StreamJsonRpc until we can figure out how to avoid this.

**Comment by AArnott** [comment]
Hi @watfordgnf. Thanks for reaching out. What is `JsonArrayPool`? Is that a newtonsoft.json class? Is the issue that you're sending large strings and newtonsoft.json caches those large strings as char arrays?

If you're sending large data like that, have you considered [using `Stream` arguments](https://github.com/microsoft/vs-streamjsonrpc/blob/master/doc/oob_streams.md) to pass that data? It would bypass newtonsoft.json entirely for that data so it would be much more efficient in a few ways.

**Comment by watfordgnf** [comment]
Yeah it is used by Newtonsoft.Json:
https://github.com/microsoft/vs-streamjsonrpc/blob/3e873ba4be48a8eec7573cfffa71fda4b6b76462/src/StreamJsonRpc/JsonMessageFormatter.cs#L909-L924

Currently the log data is not streamed and is a `string` (downstream dependency), but I guess if we wrapped that in a MemoryStream then we could utilize the Stream argument instead.

**Comment by AArnott** [comment]
Great. Using `Stream` sounds like it will resolve your issue more quickly than waiting for System.Text.Json support in this library, which has no timeline at this point.
But another good idea (can you open a new issue for this?) would be for the `JsonMessageFormatter` to more aggressively limit the size of the arrays it stores in the pool it uses than whatever the standard `ArrayPool<T>.Shared` setting is. Please mention in that new issue what sizes you're seeing stored there so we can take that into account when choosing a better limit.
