### ISSUE TITLE
Add / change serialization of JSON-RPC 1.0 messages in JsonMessageFormatter

### ISSUE THREAD

**Issue by haakoo** [microsoft/vs-streamjsonrpc#312]
`JsonMessageFormatter` handles incoming JSON-RPC messages in version 1.0 and 2.0 fine, but it seems to create invalid messages when the version is set to `1.0`.

A 1.0 response should always have the following properties ([JSON-RPC 1.0 Specification](https://www.jsonrpc.org/specification_v1)):

- `result` - The Object that was returned by the invoked method. This must be null in case there was an error invoking the method.
- `error` - An Error object if there was an error invoking the method. It must be null if there was no error.
- `id` - This must be the same id as the request it is responding to.

Now it does not create the error-object.

Similarly for 1.0 requests, that should have:

- `method` - A String containing the name of the method to be invoked.
- `params` - An Array of objects to pass as arguments to the method.
- `id` - The request id. This can be of any type. It is used to match the response with the request that it is replying to.

It also force create the `jsonrpc` property, which is only used in version 2.0.

Would it be interesting if I made a PR with changes that add/change this behaviour for 1.0 messages?

**Comment by haakoo** [comment]
After creating a test that uses JsonMessageFormatter.Serialize(..) to create the message, and then tries to deserialize the resulting message I get an error.

Test:
```csharp
[Fact]
public void MessageHaveRequiredProperties()
{
    var formatter = new JsonMessageFormatter()
    {
        ProtocolVersion = new Version(1, 0),
    };

    var jsonRequest = formatter.Serialize(new JsonRpcRequest { Id = "test", Method = "test", Arguments = null });
    var json = formatter.Encoding.GetBytes(jsonRequest.ToString(Formatting.None));
    ReadOnlySequence<byte> jsonSequence = new ReadOnlySequence<byte>(json);
    var jsonMessage = (JsonRpcRequest)formatter.Deserialize(jsonSequence);
}
```

Error / Exception:
```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Unable to deserialize JsonRpcMessage.
  Source=StreamJsonRpc
  StackTrace:
   at StreamJsonRpc.JsonMessageFormatter.Deserialize(JToken json) in C:\Users\holafsen\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 204
   at StreamJsonRpc.JsonMessageFormatter.Deserialize(ReadOnlySequence`1 contentBuffer, Encoding encoding) in C:\Users\holafsen\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 153
   at StreamJsonRpc.JsonMessageFormatter.Deserialize(ReadOnlySequence`1 contentBuffer) in C:\Users\holafsen\source\repos\vs-streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 145
   at JsonMessageFormatterTestsJsonRpc10.MessageHaveRequiredProperties() in C:\Users\holafsen\source\repos\vs-streamjsonrpc\src\StreamJsonRpc.Tests\JsonMessageFormatterTestsJsonRpc10.cs:line 21

Inner Exception 1:
JsonSerializationException: Unrecognized JSON-RPC 1.0 message ("jsonrpc" property not expected. Use protocol version 2.0.): {
  "jsonrpc": "2.0",
  "method": "test",
  "id": "test"
}
```

**Comment by AArnott** [comment]
No, this wasn't a deliberate omission. #220 asked for support to *receive* JSON-RPC 1.0 messages so that's what we focused on.
Adding further support for 1.0 isn't a priority for us, but we may entertain a PR that adds the functionality if it came with tests. The policy at the moment is to not accept external contributions, but if you're keenly interested and willing to send a PR I can check to see if we can get permission. 
We have a rather disruptive PR for this class coming up in the next few weeks so I would advise you to not get started, or focus on adding tests first, until late August.

**Comment by haakoo** [comment]
Thanks for the quick reply. I'll either create my own Formatter or just fork it for now. I'll come back to this when you've made the changes.
