### ISSUE TITLE
MessagePackSerializer not working on iOS

### ISSUE THREAD

**Issue by kurtcz** [microsoft/vs-streamjsonrpc#317]
How do I workaround error "operation not supported on this platform" on iOS in this code:

`
        public JsonRpcMessage Deserialize(ReadOnlySequence<byte> contentBuffer)
        {
            return this.compress
                ? (JsonRpcMessage)LZ4MessagePackSerializer.Typeless.Deserialize(contentBuffer.AsStream())
                : (JsonRpcMessage)MessagePackSerializer.Typeless.Deserialize(contentBuffer.AsStream());
        }
`
Author of MessagePack mentions something about AOT on his github but the link is dead...
BTW: My data objects use [DataContract] family of attributes not [MessagePackObject]

**Comment by kurtcz** [comment]
After some fiddling I have managed to get my own types registered on iOS but now MessagePack complains:

`StreamJsonRpc.Protocol.JsonRpcRequest is not registered in this resolver. resolver:CompositeResolver`

You need to decorate JsonRpcRequest and any other classes decorated with `[DataContract]` also with `[MessagePackObject]` and `[Key]` attributes. Once done you need to run the `mpc` tool (available [here](https://github.com/neuecc/MessagePack-CSharp/releases/download/v.1.7.3.6/MessagePackUniversalCodeGenerator.zip)) to generate a StreamJsonRpcResolver class that implements `global::MessagePack.IFormatterResolver` - developers will then need to call this during application startup:

`MessagePack.Resolvers.CompositeResolver.RegisterAndSetAsDefault(StreamJsonRpcResolver, other resolvers ...);`

**Comment by AArnott** [comment]
We're not going to decorate these protocol message types with MessagePack attributes until and if the library ever formally supports MessagePack.
But the lack of attributes need not block you from adding support yourself in your library. You can write your own resolver/formatter for the StreamJsonRpc.Protocol types even without attributes on them.

**Comment by kurtcz** [comment]
Please tell me how I can create my own resolver/formatter for your set of classes without the `mpc` tool.

**Comment by AArnott** [comment]
The technique isn't specific to StreamJsonRpc. Please refer to the MessagePack library documentation and forum for how to serialize custom types without attributes.

**Comment by kurtcz** [comment]
I am sorry I only found `ContractlessTypelessStandardResolver` which does not work on iOS, neither do all the other typeless, contractless, standard resolvers. (Operation is not supported on this platform). Is there any other way?

**Comment by AArnott** [comment]
@kurtcz Please raise the question on the messagepack forums. We do not support MessagePack in this library today and have not solved these problems ourselves yet.

I happen to be a contributor MessagePack, so if you file an issue I'll try my best to at least give you pointers.
