### ISSUE TITLE
unity supported?

### ISSUE THREAD

**Issue by zh99998** [microsoft/vs-streamjsonrpc#327]
I extract StreamJsonRpc.dll and Microsoft.VisualStudio.Validation.dll from nuget package to assets folder. then it says 

```
The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```

**Comment by AArnott** [comment]
We haven't tested it. But I don't see why it wouldn't work. Maybe you laid out the files wrong?

**Comment by zh99998** [comment]
I put `StreamJsonRpc.dll` and `Microsoft.VisualStudio.Validation.dll` in `Assets/`

using StreamJsonRpc => no error
using Microsoft.VisualStudio.Validation => `The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)`

new JsonRpc =>
```
Assets/Scripts/Lobby/Main.cs(21,27): error CS1705: Assembly 'StreamJsonRpc' with identity 'StreamJsonRpc, Version=2.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Comment by AArnott** [comment]
Which version of streamjsonrpc are you using? And which TFM (the folder under lib) are you using? You might try a streamjsonrpc package that targets net46 (the 2.0 version did this) and use the dll under lib\net46 to see if that works better.

**Comment by zh99998** [comment]
I can't find lib/net46, do you mean ·lib/netstandard2.0·?

netstandard2.0 version can pass that error, and showing more missing dependency.
after I put all dependencies into Assets directory, compile successful but got a runtime error:

`Unloading broken assembly Assets/StreamJsonRpc.dll, this assembly can cause crashes in the runtime`

**Comment by AArnott** [comment]
No, I mean net46. I mentioned you need to look at the 2.0 version. If you're only seeing lib/netstandard2.0 then you're looking at the 2.1 version.
Download [the v2.0.208 version](https://www.nuget.org/packages/StreamJsonRpc/2.0.208) and use the one in the lib\net46 directory and see if that helps.

StreamJsonRpc has more dependencies than just itself and Microsoft.VisualStudio.Validation.dll. You need all of them to work in Unity or anywhere else. Using `nuget.exe install StreamJsonRpc` will download the transitive closure of dependency packages into the current directory. But again you may want to supply the version parameter to that command to specify that you want 2.0.208 (or even 1.5.68 for fewer dependencies).

**Comment by zh99998** [comment]
StreamJsonRpc net46 version with dependencies netstandard2.0 version 
=>
`Unloading broken assembly Assets/StreamJsonRpc.dll, this assembly can cause crashes in the runtime`

I Can't net46 version for all dependencies, for example System.Buffers looks like only have .netstandard version, I have tried downgrade.

**Comment by AArnott** [comment]
If you start with streamjsonrpc 2.0.208 and follow the dependencies for its net46 target, you'll find that *all* the dependencies support net46 or older. System.Buffers in particular offers a net45 target.

One thing you could do is start VS and create a net46 targeting console application. Then use the NuGet GUI to install StreamJsonRpc 2.0.208 to your project, and build. The bin folder will then get the .exe (which you can ignore) and all the .dll's that streamjsonrpc.dll will require at runtime. If you copy those to your Assets folder, you might have better luck.

**Comment by zh99998** [comment]
> One thing you could do is start VS and create a net46 targeting console application. Then use the NuGet GUI to install StreamJsonRpc 2.0.208 to your project, and build. The bin folder will then get the .exe (which you can ignore) and all the .dll's that streamjsonrpc.dll will require at runtime. If you copy those to your Assets folder, you might have better luck.

I tried this and got `Loading assembly failed: "Assets/System.Net.Http.dll"`.
`System.Net.Http.dll` is in Assets directory and it's copied from bin directory.

**Comment by AArnott** [comment]
Well, I don't know then. Sorry. As I say, we've never tried this and don't support unity as a target.
