### ISSUE TITLE
Add support for IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#328]
[`IAsyncEnumerable<T>` is here](https://apisof.net/catalog/System.Collections.Generic.IAsyncEnumerable%3CT%3E) and it's a more natural fit than `Progress<T>` when the RPC method wants to exchange data *as* its result instead of simply reporting progress *about* its result.

We should add support for it.

For downlevel framework versions, this type is defined in the [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces) package.

In the spec here, we use the term `generator` to refer to the app-level implementation of `IAsyncEnumerable<T>` that produces the values, and `consumer` to refer to the app-level enumeration of those values. We avoid the terms `server` and `client` because the `IAsyncEnumerable<T>` may be passed to the server via an RPC method argument or passed to the client via an RPC return value.

## Sample use case

A server method which returns an async enumeration may be defined as:

```cs
IAsyncEnumerable<int> GenerateNumbersAsync(CancellationToken cancellationToken);
```

Per C# 8 syntax this may be consumed via:

```cs
await foreach (int number in this.clientProxy.GenerateNumbersAsync(token))
{
    Console.WriteLine(number);
}
```

The server method may be implemented in C# 8 as:

```cs
public async IAsyncEnumerable<int> GenerateNumbersAsync([EnumeratorCancellation] CancellationToken cancellationToken)
{
    for (int i = 1; i <= 20; i++)
    {
        cancellationToken.ThrowIfCancellationRequested();
        await Task.Yield();
        yield return i;
    }
}
```

We must support methods which return `IAsyncEnumerable<T>`.
We *may* also support methods which take `IAsyncEnumerable<T>` as parameters.

## State machine internals

The following describes how `IAsyncEnumerable<T>` return types will be supported. `IAsyncEnumerable<T>` method parameters may be supported later.

1. Client invocation results in an RPC call, and the server invokes the method that returns an `IAsyncEnumerable<T>`. A C# async-iterator method will return this object without executing user code within the method. The resulting `IAsyncEnumerable<T>` object will be immediately converted to an `IAsyncEnumerator<T>` object by the RPC server and this object will be retained. A handle to this enumerator instance will be returned to the RPC client.
1. The RPC client exposes an `IAsyncEnumerable<T>` object to the caller, whose `GetAsyncEnumerator` method will only work once. Subsequent calls to this method will throw `InvalidOperationException`. To repeat the enumeration, the RPC client should call the RPC method again.
1. When the RPC client application calls `IAsyncEnumerable<T>.GetAsyncEnumerator(CancellationToken)`, the RPC client library produces an `IAsyncEnumerator<T>` instance which handles the RPC layer and emulates a local async enumerator. The `CancellationToken` passed to it applies to each RPC call to the server when asking for more value(s).
1. When the client application calls `DisposeAsync` on the `IAsyncEnumerator<T>`, an RPC call is made to the server so the server can release the memory holding the server's original `IAsyncEnumerator<T>` in memory.

If the originating request or a subsequent request for values is ever canceled, this cancels the entire enumerator. It is not possible to obtain more values after a request for more values is canceled. However clients must still dispose of the enumerator if they ever received the enumerator handle in response to their originating request.

When the client makes the request on a dynamically generated proxy, and the method returns `IAsyncEnumerable<T>` directly (not wrapped in `Task<T>`), the RPC client proxy will have to create an `IAsyncEnumerable<T>` implementation that is available immediately, and ends up waiting for the async RPC call to complete before returning from the proxy's private implementation of `IAsyncEnumerator<T>.MoveNextAsync()`.

## Performance tuning

The `IAsyncEnumerator<T>` interface is defined assuming that every single value produced may be acquired asynchronously. Thus an RPC implementation of this feature might be that every request for a value results in an RPC call to request that value. Such a design would minimize memory consumption and cost of generating values unnecessarily, but would be particularly noisy on the network and performance would suffer on high latency connections. 

To improve performance across a network, the RPC layer will support:

1. Batching: When the consumer requests a value from the generator, the server may respond with the next several values in the same response message in order to reduce the number of round-trips the client must make while enumerating the sequence. This improves performance when network latency is significant.
1. Read ahead: The generator will do work to produce the next value(s) _before_ receiving the consumer's request for them. This allows for the possibility that the server is processing the data while the last value(s) are in transit to the client or being processed by the client. This improves performance when the time to generate the values is significant.

The above optimizations are configured individually, and may be used in combination.

To accomplish this, we define these properties which tune the RPC bridge for async enumerables:

```cs
        /// <summary>
        /// Gets or sets the maximum number of elements to read ahead and cache from the generator in anticipation of the consumer requesting those values.
        /// </summary>
        public int MaxReadAhead { get; set; }

        /// <summary>
        /// Gets or sets the minimum number of elements to obtain from the generator before sending a batch of values to the consumer.
        /// </summary>
        public int MinBatchSize { get; set; } = 1;
```

The default values for these properties will result in the same behavior as one would observe with `IAsyncEnumerable<T>` without any RPC: one value is produced or consumed at a time. 
Individual services may choose based on expected use cases and performance costs to change these values to improve the user experience.

These properties are defined on the new `JsonRpcEnumerableAttribute`, which may be applied on the  return type of a server method implementation. It will be ignored if used within an interface declaration. For example, the aforementioned C# 8 server method may be defined like this in order to provide all the values to the client in batches of 10:

```cs
[return: JsonRpcEnumerable(MinBatchSize = 10)]
public async IAsyncEnumerable<int> GenerateNumbersAsync([EnumeratorCancellation] CancellationToken cancellationToken)
{
    for (int i = 1; i <= 20; i++)
    {
        cancellationToken.ThrowIfCancellationRequested();
        await Task.Yield();
        yield return i;
    }
}
```

A batch size of 10 with the default `MaxReadAhead` value of `0` means the server will not produce any values until the client requests them, but when the client requests them, the client will get 10 or the rest of the sequence, whichever is fewer.

Suppose `MaxReadAhead = 15` and `MinBatchSize = 10`. After the client calls `GenerateNumbersAsync` but before it asks for the first element in the sequence, the server is already generating values till it fills a cache of 15. When the client request comes in for the first value(s), the server will wait till at least 10 items have been produced before returning any to the client. If more than 10 were cached (e.g. the server was able to produce all 15 as part of "read ahead"), the client will get all that are cached. After the client's request is fulfilled, the read ahead server will continue generating items till the read ahead cache is full, in preparation for the next client request.

In short: `MinBatchSize` guarantees a minimum number of values the server will send to the client except where the sequence is finished, and `MaxReadAhead` is how many values may be produced on the server in anticipation of the next request from the client for more values.

The state machine and any cached values are released from the generator when the `IAsyncEnumerator<T>` is disposed.

### Originating request 

The original RPC request to the `IAsyncEnumerable<T>` returning method includes a special `expect: "enumerableResponse"` property to indicate to the server that it is capable of understanding the lifetime requirements of the returned object. This is important because upon successful completion of this particular RPC call, the server will now retain memory on behalf of the client that may be a memory leak if the client never follows up with another call to the server to release the memory. 
An RPC call to an `IAsyncEnumerable<T>`-returning method that lacks this property should result in the server returning an error response and not invoking the method.

```json
{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "GenerateNumbersAsync",
   "params": [ "some", "parameters"],
   "expect": "enumeratorResponse",
}
```

If the request omits the `id` property, the client will not get a result, and the server should either reject the request or execute the method but discard the result without leaking memory.

### Originating result

A successful result provides the handle to the server's enumerator, which may be any valid JSON token except `null`:

```json
{
   "jsonrpc": "2.0",
   "id": 1,
   "result": "enum-handle"
}
```

### Client request for values

A request for value(s) from the client:

```json
{
   "jsonrpc": "2.0",
   "id": 2,
   "method": "rpc.Enumerator.next",
   "params": { "token": "enum-handle" },
}
```

### Server response with values

A response with value(s) from the server always comes in an array, even if only one element is returned:

```json
{
   "jsonrpc": "2.0",
   "id": 2,
   "result": {
      "values": [ 1, 2, 3 ],
      "finished": false
   }
}
```

Note the `finished` property is a hint from the server for when the last value has been returned. 
The server *may* not know that the last value has been returned and should specify `false` unless it is sure the last value has been produced. 

The client *may* ask for more values without regard to the `finished` property, but if `finished: true` the client may optimize to not ask for more values but instead go directly to dispose of the enumerator.

The server should never return an empty array of values unless the last value in the sequence has already been returned to the client.

### Client disposes enumerator

The client always notifies the server when the local enumerator proxy is disposed. This is typically a notification (it has no `id` property).

```json
{
   "jsonrpc": "2.0",
   "method": "rpc.Enumerator.dispose",
   "params": { "token": "enum-handle" },
}
```

**Comment by AArnott** [comment]
I'm working on this over at https://github.com/aarnott/vs-streamjsonrpc/tree/asyncenum

**Comment by AArnott** [comment]
I'd love to get a review of this spec from folks from each of these feature areas:

Corefx: @davidfowl
C#: @sharwell 
LSP: @dbaeumer, @tinaschrepfer  

Mentioned folks: Can you please either review or suggest someone who would be more appropriate? (Or if you're the best person, but you're not interested, that's OK too).

**Comment by sharwell** [comment]
I don't see any issues here, but should probably get someone from @dotnet/roslyn-compilers to review as well. /cc @jaredpar

**Comment by dbaeumer** [comment]
@AArnott: why is this different from a generic IProgress implementation to stream results back to the client?

**Comment by AArnott** [comment]
Great question, @dbaeumer. Whereas `IProgress<T>` is a *push* model, `IAsyncEnumerable<T>` is a pull model. It allows the client to determine how much and the rate at which data is sent to it.
For example, consider a `git history` command or an LSP completion list. Both of these could potentially have many thousands of results, yet the user can only see the first several until and if they page down in the list. `IProgress<T>` is a poor fit for this because the server will keep sending tons of data that the client may never care for. The client could cancel the request to abort the server's transmission, but then when the user hits page down, we have to come up with some way to resume, or the server has to start all over. Compare this with `IAsyncEnumerable<T>` where the client can simply enumerate the first 20 or so items, and then when the user hits page down, the client can continue the enumeration.

Pagination APIs are the classic way to solve this: add parameters to indicate how many items to skip and how many to return. This is harder to use, and presents a problem if the data underneath changed in between queries, leading to creation of a "handle" to a particular version of data that the server and client must pass back and forth in order to progressively build a consistent list. `IAsyncEnumerable<T>` basically makes this "handle" a built-in part of the RPC library and protocol so that from a consumer's point of view it just feels like natural C#.

In TypeScript I imagine this exact same protocol could be manifest as a node.js object stream that is in pull mode instead of push mode.

**Comment by dbaeumer** [comment]
@AArnott thanks for the great explanation. I am still unsure why the implementation in terms of how tokens are used is different from the IProgress<T> implementation. I would have expected something like this:

```
{
   "jsonrpc": "2.0",
   "id": 1,
   "method": "GenerateNumbersAsync",
   "params": [ "asyncResultToken", "some", "parameters", ]
}
```

I am not sure if it is a good idea to add additional top level properties to an RPC message. I am worried if someone implements some sort of forwarding these properties might get lost.

**Comment by AArnott** [comment]
@dbaeumer: why would the client be passing *in* a token when the server *returns* the `IAsyncEnumerable<T>` object? Per the JSON-RPC spec, injecting an additional arg would change the receiving method's signature. But the server method doesn't take a parameter for a handle to something it's going to return. I want the C# (or TypeScript) method to just be natural:

```cs
public IAsyncEnumerable<int> GetNumbers(int minimum, int maximum) { }
```

If the method now took a `string token` parameter, what would it even do with it?
This, like `IProgress<T>`, is designed so that the common language constructs and patterns Just Work. People expect to be able to return an enumerable from a C# iterator method and for the caller to be able to foreach over it. I want that to work over RPC without the app layer having to do anything special.

> I am not sure if it is a good idea to add additional top level properties to an RPC message. I am worried if someone implements some sort of forwarding these properties might get lost.

Yes, that's a risk. I don't know how to do it any better though. The added property certainly adds complexity to my implementation too, but without it we risk the server suffering a memory leak if clients aren't well-behaved. Maybe it's worth that risk, since the client is calling the method they supposedly know about it (and hopefully the proper way to call and dispose of the result). But the idea that calling an RPC method opening state that doesn't automatically close is unprecedented as far as I know, so I hesitate before opening that.

**Comment by dbaeumer** [comment]
> why would the client be passing in a token when the server returns the IAsyncEnumerable<T> object?

For me there are two reason:

- consistency with other cases where we use token which usually come from the caller
- easier to handle cases were the create call doesn't return. The client could still send a dispose and the server would know how to handle it assuming that the token is unique. If the server provides the token you actually don't know whether you have a leak or not.

In LSP I do this for example if a server want to initiate progress. It opens state on the client but the server manages the token. If the request to create the progress fails, errors or times out the server can send a dispose request using the token it generated. 

> Per the JSON-RPC spec, injecting an additional arg would change the receiving method's signature.

I think that is the difference between JSON-RPC and the server libraries I have in LSP. The JSON-RPC would have the additional property and that would be the JSON RPC signature and the LSP specification. In the LSP implementation layer I would convert this to an async function not having the first argument. This is what I do for progress and stream as well.

**Comment by AArnott** [comment]
> consistency with other cases where we use token which usually come from the caller

For me, consistency is that the token comes from the party that is passing the special object, and which therefore the other party needs in order to address that object. In the `Progress<T>` case the token comes from the client because the client passes the Progress object in, and the server then sends messages to the client.
In this case, the special object comes from the server and the client uses the token to call the server (it's the reverse direction in every since), so consistency would mean the server generates the token (which is also reversed from the Progress feature).

Also, I'd like to find a way for clients to pass in `IAsyncEnumerable<T>` objects as arguments. So it won't always be a return value from an RPC method. In that case, the receiver of the object of course couldn't generate the token because the client sends the object with the initial communication. So in that case the token obviously must come from the client (who is sending the object). 

Rather than have client always generate the token, both for cases where it sends as well as receives the enumerable object (which would make for some pretty bizarre coding IMO), and have a weird method signature in the JSON-RPC message which the library then "hides", I'd rather do what we do for `IProgress<T>` which is to represent the special object by a token, which is in the proper place with regard to the method parameter position or method result.

> The client could still send a dispose and the server would know how to handle it assuming that the token is unique. If the server provides the token you actually don't know whether you have a leak or not.

I think I could solve this problem by slightly strengthening the language around cancellation. I already state in the spec that cancellation from the client should terminate the enumeration, and while the client "should" still dispose of the enumeration I could state that the server should clean up any memory even without that.

> This is what I do for progress and stream as well.

What is this "stream" support you have? Is it anything like #334 ?

**Comment by AArnott** [comment]
So it turns out that my earliest implementation actually makes `IAsyncEnumerable<T>` work when passed as an argument as well (I thought I'd have to do more work to support that before it worked).
But unlike an RPC method that *returns* the object, where I can apply a `[return: JsonRpcEnumerable()]` attribute, when the client passed in an enumerable, there's not a clear way for the client to indicate the settings to use. Any ideas?

**Comment by AArnott** [comment]
I think I'll use the decorator pattern:

```cs
await rpcProxy.PassInSequenceAsync(myEnumerable.WithJsonRpcSettings(mysettings));
```

This would also work with return values, although it would require an extra thunking method to wrap a C# async iterator method. So we may still want to support the `[return: ]` attribute syntax for convenience. We happily don't need syntax sugar like that for passing in arguments since it's trivially easy to add that extension method call.

Also: this makes me consider we could wrap *any* `IEnumerable<T>` with an extension method in order to direct `JsonRpc` to treat it as an async enumerable instead of serializing its entire content for inline inclusion in the original message.

**Comment by davidfowl** [comment]
The more I see this the more I wonder if this project should use signalr instead 😄. There seems to be lots of feature overlap.

**Comment by AArnott** [comment]
@davidfowl: thanks for the looking.

Does SignalR work on net472/netstandard2.0? Does it work over arbitrary streams or does it require HTTP/2? Does it work in node.js?
I know *very* little about SignalR, so if it passes all those checks, I guess I should look into it. But IIRC every time I've seen it it read "ASP.NET" all over it, which makes me suspect it's focused on web scenarios, and this library is decidedly *not* for web in particular (although we can and do use it over a websocket).

**Comment by dbaeumer** [comment]
Stream  === Streaming :-)

Using `IAsyncEnumerable<T>` objects as arguments is a fair point.

Now that I think about it again I believe your proposal can only be implemented in a nice way if the used programming language supports generator functions. So may be this is something that should be kept local to your usage of JSON RPC. In LSP I need to support language that don't have generator functions. I think this is nothing I can tackle in the near future.

Side note: I noticed that you use `.` (e.g. ``) as a namespace separator whereas for progress and cancellation ( and in LSP) we use '/'.

**Comment by AArnott** [comment]
> Side note: I noticed that you use . (e.g. ``) as a namespace separator whereas for progress and cancellation ( and in LSP) we use '/'.

The JSON-RPC [spec prescribes](https://www.jsonrpc.org/specification#extensions) `rpc.` as a prefix for RPC extensions. So that already puts me in a `.`-delineated world if I consider this to be a spec extension. But I may be flexible on this point.

> So may be this is something that should be kept local to your usage of JSON RPC. In LSP I need to support language that don't have generator functions. I think this is nothing I can tackle in the near future.

I don't think this feature's applicability relies on generator functions. On the contrary in fact, and as I mentioned [here](https://github.com/microsoft/vs-streamjsonrpc/issues/328#issuecomment-557299677) I believe *any* collection can easily opt in to this kind of special treatment. So you hardly need generator functions. Have a huge collection you want to send to the other party but the other party may only one some of it? Wrap the collection with an async enumerable object decorator and the JSON-RPC library will automatically send just a handle to the other party so they can consume it incrementally and only as much as they want. Javascript has arrays of course, and this makes this feature just as applicable to arrays as C# generator functions.
And as far as consumption, yes the JSON-RPC library that receives the handle needs the code to convert that handle into an enumerable thing, but that doesn't require generator functions.

**Comment by dbaeumer** [comment]
You are correct. Having some sort of iterator would be enough to implement that.

I always interpreted the `rpc. extension as something the RPC spec owns. So I stayed away from this. But given that they use . we might want to think about using `$.progress` (which is not final in LSP yet) and support `$.cancel`. What do you do in your implementation.

**Comment by AArnott** [comment]
> I always interpreted the rpc. extension as something the RPC spec owns. 

I'm not sure what their intent is. But as the JSON-RPC 2.0 spec doesn't appear to have any further development, it seems `rpc.` is most likely intended for 3rd party extensions.

> we might want to think about using $.progress (which is not final in LSP yet) and support $.cancel. What do you do in your implementation.

`$.progress` wouldn't conform to the `rpc.` prefix, so I don't see any value in changing it. And changing from `$/progress` to *anything* comes with a cost, as we've already shipped stable versions of this library with progress support. So I'd rather not change it at this point. But ya, by the same reasoning that I'm using on this issue, perhaps it should have been `rpc.progress`.

For cancellation we use `$/cancelRequest` which I believe we got either from you or Live Share. We generally want to interop with what was already out there so that too I didn't want to change just for the sake of conforming to one interpretation of the spec.

**Comment by dbaeumer** [comment]
Wow, today it not my day. Too many things in parallel. You are right, I :-) speced cancellation as `$/cancelRequest`. 

> I didn't want to change just for the sake of conforming to one interpretation of the spec

Fully agree. So may be we then stick to `$` for our extensions to JSON-RPC.

**Comment by AArnott** [comment]
> So may be we then stick to $ for our extensions to JSON-RPC.

If you're suggesting I use `$/` instead of `rpc.` as the prefix for *this* spec, I'm open to that. Perhaps `$/enumerator/next` and `$/enumerator/dispose`?

**Comment by dbaeumer** [comment]
`$/enumerator/next` and `$/enumerator/dispose` sounds good to me.

**Comment by AArnott** [comment]
This feature work is done. Here is the [official spec and behavior](https://github.com/microsoft/vs-streamjsonrpc/blob/master/doc/asyncenumerable.md) of it. The spec proposed in this issue is slightly out-dated and should be disregarded at this point.

Also note my #384 proposal that modifies it slightly.
