### ISSUE TITLE
Simple example using a websocket connection

### ISSUE THREAD

**Issue by mthgr** [microsoft/vs-streamjsonrpc#349]
I'm looking for a basic example showing how to use this library with a WebSocket connection and ideally showing how to receive notifications.

Is there an example somewhere?

Thanks.

**Comment by AArnott** [comment]
Our docs link to [this sample](https://github.com/AArnott/StreamJsonRpc.Sample?files=1) which includes websockets. It also discusses notifications. Have you reviewed those? If so what specific questions do you have?

**Comment by mthgr** [comment]
Thank you for the prompt reply.

Yes. I went through everything I could find.

I also reviewed all the issues discussing Websockets.

But as far as I know and can find online the Microsoft Websocket has no
stream?

I'm looking for a code sample that shows how to establish a websocket
connection (the simplest example possible using Microsoft classes only) and
how to use it with vs-streamjsonrpc. A console application ideally.

I'm really new to this and all the examples I can find online use
third-party libraries to establish websocket connections.

Any help would be appreciated.

**Comment by AArnott** [comment]
I see. I guess my sample only shows a CLR websocket server that uses JSON-RPC and a *javascript* websocket client for it. You want a CLR-based websocket client, is that right?

**Comment by mthgr** [comment]
Yes.

That would be great !

Mathieu


Le dim. 20 oct. 2019 à 10:16, Andrew Arnott <notifications@github.com> a
écrit :

**Comment by AArnott** [comment]
[Here you go](https://github.com/AArnott/StreamJsonRpc.Sample/blob/a756dab2df249340bb8c2deaf284e3c59107da90/StreamJsonRpc.Sample.WebSocketClient/Program.cs#L39)

**Comment by mthgr** [comment]
Thank you I really appreciate this!

Mathieu


Le lun. 21 oct. 2019 à 02:03, Andrew Arnott <notifications@github.com> a
écrit :
