### ISSUE TITLE
Server methods not called

### ISSUE THREAD

**Issue by vitidev** [microsoft/vs-streamjsonrpc#366]
I don't understand.

Test server:

	internal class Program
    {
        private static readonly TcpListener Listener = new TcpListener(IPAddress.Parse("127.0.0.1"), 3333);

        private static void Main(string[] args)
        {
            Listener.Start();
            Listener.BeginAcceptTcpClient(Callback, null);
            Console.ReadLine();
        }

        private static void Callback(IAsyncResult ar)
        {
            var tcpClient = Listener.EndAcceptTcpClient(ar);
            var rpc = new JsonRpc(tcpClient.GetStream());
            rpc.TraceSource.Switch.Level = SourceLevels.All;
            rpc.TraceSource.Listeners.Add(new DefaultTraceListener());
            rpc.AddLocalRpcTarget(
                new Server(),
                new JsonRpcTargetOptions
                {
                    AllowNonPublicInvocation = false
                });
            rpc.StartListening();
        }

        public class Server
        {
            [JsonRpcMethod("test")]
            public void Test()=> Debug.WriteLine("test");
        }

Test client:

    class Program
    {
        static void Main(string[] args)
        {
            var tcp = new TcpClient("127.0.0.1", 3333);
            var json ="{\"jsonrpc\": \"2.0\", \"method\": \"test\", \"params\": [], \"id\": 1}\r\n";
            var bytes = Encoding.ASCII.GetBytes(json);
            tcp.GetStream().Write(bytes, 0, bytes.Length);
            tcp.GetStream().Flush();
            Console.WriteLine("Hello World!");
        }
    }

in output:

      JsonRpc Information: 0 : Added local RPC method "test" -> StreamJsonRpc.MethodSignatureAndTarget
      JsonRpc Information: 0 : Added local RPC method "test" -> StreamJsonRpc.MethodSignatureAndTarget
      JsonRpc Information: 3 : Listening started.
      JsonRpc Information: 3 : Listening started.

what's wrong? Method was not called and no information is provided

If remove \r from json I get

    JsonRpc Critical: 13 : Connection closing (StreamError: ... BadRpcHeaderException: Header does not end with expected  character sequence:
    {"jsonrpc": "2.0", "method": "test", "params": [], "id": 1}). StreamJsonRpc.BadRpcHeaderException: Header does not end with expected

which means that it is reading from the stream , but no more

**Comment by AArnott** [comment]
You're missing the http headers that the default configuration uses to introduce each json message. See [relevant docs](https://github.com/microsoft/vs-streamjsonrpc/blob/master/doc/extensibility.md#message-handlers)
