### ISSUE TITLE
Convey cancellation result to client when requests are canceled

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-streamjsonrpc#38]
Now that https://github.com/Microsoft/language-server-protocol/issues/63#issuecomment-302204773 has been resolved, we can apply the pattern to our library.

**Comment by AArnott** [comment]
Try to throw `TaskCanceledException` in this case with the caller's `CancellationToken` set on it.

**Comment by AArnott** [comment]
Point to call out to @heejaechang respecting #67, that this will still throw `RemoteInvocationException` if the server-side actually failed at doing something. This change we're proposing here is to mirror what a local CLR call would make: if it fails, we propagate that failure. But if it cancels itself (by throwing `OperationCanceledException` on the remote side) then we will also throw `OperationCanceledException` on the local side.

**Comment by AArnott** [comment]
@heejaechang how badly do you want this change in 15.6?

**Comment by heejaechang** [comment]
this one is okay. we want this more - https://github.com/Microsoft/vs-streamjsonrpc/issues/64
