### ISSUE TITLE
Getting a StreamJsonRpc.RemoteInvocationException when invoking a server->client RPC on Mono.

### ISSUE THREAD

**Issue by ILikePizza555** [microsoft/vs-streamjsonrpc#387]
Minimal source code that reproduces this error: https://github.com/ILikePizza555/StreamJsonRPCTest

This happens on MacOS on the latest version of Mono (6.4.0.198).

Output of the project is

```
Entered RequestDataFromServerRPC
Entered RequestDataFromClientRPC
RPC Exception: StreamJsonRpc.RemoteInvocationException: Attempted to access an element as a type incompatible with the array.
  at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult] (System.Nullable`1[T] id, System.String targetName, System.Collections.Generic.IReadOnlyList`1[T] arguments, System.Threading.CancellationToken cancellationToken, System.Boolean isParameterObject) [0x0018d] in <ab9df841741b4f729c437e4366755293>:0 
  at SJRTest.Server.RequestDataFromClientRPC (System.String key, System.Threading.CancellationToken ct) [0x0009b] in <33bed87fd5be4d728d3def5bfad1c0af>:0 
Result: 
```

Obviously, the expected behavior is to not have the exception. The fact that the application does not print out `Entered DictionaryDataCallback` indicates that this exception is thrown before the method is called.

**Comment by AArnott** [comment]
I am pleased to say this reproduces on Windows with the mono runtime as well.
I'll try to get our unit tests running on mono so we can offer better mono support. But please do file a bug against mono as well and link to this issue so we can track.

**Comment by AArnott** [comment]
Mono is struggling to run our unit tests for a variety of reasons. For just our `JsonRpcJsonHeadersTests` class, 31 of 145 tests fail, including with the exception that this issue tracks.

**Comment by AArnott** [comment]
I found an even smaller repro for your project. I've sent [a PR](https://github.com/ILikePizza555/StreamJsonRPCTest/pull/1).

**Comment by AArnott** [comment]
I filed https://github.com/mono/mono/issues/17993 to track the defect on mono

**Comment by AArnott** [comment]
I also filed https://github.com/mono/mono/issues/17994 to track the only other defect on mono that I found.
