### ISSUE TITLE
General way for clients to invoke instance methods on short-term objects on the server

### ISSUE THREAD

**Issue by NickRedwood** [microsoft/vs-streamjsonrpc#390]
From what I've seen looking through the vs-streamJsonRpc code and readme files so far, the server object is always a single object instance that exists for the life of the rpc object. However what if the server is instead continually creating instances of objects and we want to tell the client about those and have the client call methods on specific instances? And then dispose those instances too?

There does not seem to be a facility to give objects IDs which are transmitted over the stream to enable this. I realise the RPC spec may be more about calling unchanging method names rather than methods on specific object instances, but nevertheless how would I go about this?

My example is as follows. I still have a main server object, which broadcasts to clients that it has some availability to do work by sending instances of the `IWorkerOffer<T>` below to the clients.

```
public interface IWorkerOffer<TWorker>
{
	Task<(Boolean Success, TResult Result)> TryAccept<TResult>(ISerializableWorkFunction<TWorker,TResult>  work)
}
```
There may be multiples of these at any one time, not just one. The details aren't important, but the critical thing is that when the client side calls `TryAccept` it is sent back to the server and invoked against the right instance of `IWorkerOffer`.

So to try achieve this I've looked at rpc instance methods like `Attach` or `AddLocalRpcTarget`, but neither seem like they're able to call a specific object instance (in the latter case I'm referring to the method note 'The target object(s) ... are invoked in the order which they are added.').

My fallback option is to do it manually, store the `IWorkerOffer`s broadcast in a `ConcurrentDictionary` or similar with a generated object ID, then match incoming requests against those. So add a method to the server class that looks approximately like the following:

`Task<(Boolean Success, TResult Result)> TryAccept<TResult>(integer offerId, ISerializableWorkFunction<TWorker,TResult>  work)`

Is that manual approach the only way to do this or is there something built into this rpc framework that I'm missing?

**Comment by AArnott** [comment]
What you're asking for is not supported by JSON-RPC or this library, and represents a very significant feature request. I'm not even aware of any RPC library that supports the concept of marshaling additional objects which may then be remotely called except for .NET Remoting, which is now deprecated.

We might one day reach for it here, but for the foreseeable future we have no plan to try for it.

**Comment by NickRedwood** [comment]
Ok thanks for the response, I will find a way to do what I need using the existing framework.
