### ISSUE TITLE
The "Project Site" URL of the NuGet package is not correct

### ISSUE THREAD

**Issue by CXuesong** [Microsoft/vs-streamjsonrpc#40]
Ref = https://www.nuget.org/packages/StreamJsonRpc/
When clicking the "Project Site" link to the left side, I got linked to `Microsoft/vs-threading`…

See [StreamJsonRpc.csproj#L15](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/StreamJsonRpc.csproj#L15).

**Comment by AArnott** [comment]
Thanks for reporting.
