### ISSUE TITLE
[loc][Query][vs-streamjsonrpc] 0; "ElementsAlreadyPrefetched"

### ISSUE THREAD

**Issue by PDostalek** [microsoft/vs-streamjsonrpc#403]
Hello developers,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question.

Source:
This enumeration has already prefetched elements once.

ID & File Name:
0; "ElementsAlreadyPrefetched"
src\StreamJsonRpc\xlf\Resources.xlf

Query:
Does "once" mean "one time" or "sometime in the past"?

**Comment by AArnott** [comment]
Sometime in the past.
