### ISSUE TITLE
Remoted stream may not be released before remoted call returns

### ISSUE THREAD

**Issue by tabascq** [microsoft/vs-streamjsonrpc#419]
I have a method like CopyDataToStreamAsync(Stream stream, CancellationToken cancellationToken). I pass that method the stream for a file that is opened for write, and when the call returns I rename the file.

Sometimes, the file rename fails because it is still locked, suggesting that the stream proxy still has a lock on that file. Strategically placed breakpoints interrupt the flow of execution such that the rename succeeds, suggesting that it is a timing issue.

**Comment by AArnott** [comment]
This behavior is by design. I'll add docs to explain the right way to go.
