### ISSUE TITLE
Client reconnection best practices

### ISSUE THREAD

**Issue by tehnetaholic** [microsoft/vs-streamjsonrpc#421]
Hi!
I have read docs but its still unclear to me how I should cleanup closed connection and how I should reconnect. Let's say I have a client and I would like to have a single instance of it which is reused in different parts of the application.

    public async Task<ISignService> CreateClientProxy()
    {
                var socket = new ClientWebSocket();
                await socket.ConnectAsync(new Uri(coinConfig.KvServiceUrl), new CancellationToken());
                var jsonRpc = new JsonRpc(new WebSocketMessageHandler(socket));
                jsonRpc.StartListening();
                jsonRpc.Disconnected += OnDisconnected;
                var proxy = jsonRpc.Attach<ISignService>();
                return proxy;
    }|

Let's say that I keep track of ClientWebSocket object, JsonRpc object, and a proxy object and make sure that they exist in a single instance.
when `Disconnected` is fired should I:
- dispose ClientWebSocket?
- unsubscribe jsonRpc.Disconnected from an event handler?
- dispose jsonRpc?
- remove references to proxy object, so it could be garbage collected?
- recreate a socket connection?
- recreate a JsonRpc object?
- generate a new Proxy?
Thanks!

**Comment by AArnott** [comment]
In `Disconnected` you can dispose of `ClientWebSocket`, yes.
No need to unsubscribe from the event handler.
Yes, you should dispose JsonRpc (but know that this is an area we've got work to do #246)
You can remove the proxy reference to allow GC if you'd like, but unless you're holding many of them in memory at once, I wouldn't worry _too_ much.
And yes, you need to recreate everything for each new connection.
