### ISSUE TITLE
Is it possible to change the default behavior to send request with parameter Object ?

### ISSUE THREAD

**Issue by mthgr** [microsoft/vs-streamjsonrpc#423]
I'm connecting to an existing server (not implemented with vs-streamjsonrpc) over websocket and the following code works as expected (see trace):

```cs
object myResult = await jsonRpc.InvokeWithParameterObjectAsync<object>("getCustomerProperties"", new { customerid = "102", property_names = new[] { "name" }});
```

```
TraceSourceApp Information: 8 : {"id":2,"method":"getCustomerProperties""}
TraceSourceApp Verbose: 8 : Sent: {
  "jsonrpc": "2.0",
  "id": 2,
  "method": "getCustomerProperties"",
  "params": {
    "customerid": "102",
    "property_names": [
      "name"
    ]
  }
}
```

On the other hand, the following code doesn't work (I'm trying to implement a strongly typed version of the above code using the example in the documentation) and the server return an error:

```cs
interface IServer
{
    Task<object> getCustomerProperties(string customerid, string[] property_names);
}

public class Server :IServer
{
    public Task<object> getCustomerProperties(string customerid, string[] property_names)
    {
    }
}

IServer server = jsonRpc.Attach<IServer>();

jsonRpc.StartListening();

var rest = await server.getCustomerProperties("102", new[] {"name"});
```

```
TraceSourceApp Information: 8 : {"id":2,"method":"getCustomerProperties"}
TraceSourceApp Verbose: 8 : Sent: {
  "jsonrpc": "2.0",
  "id": 2,
  "method": "getCustomerProperties",
  "params": [
    "102",
    [
      "name"
    ]
  ]
}
```

The remote server throws this:

StreamJsonRpc.RemoteInvocationException: .JSONArray cannot be cast to JSONObject

Thanks!

**Comment by AArnott** [comment]
Yes, we support this. Set this property to `true` on the `JsonRpcProxyOptions` object you can pass to the `Attach<T>` method:

https://github.com/microsoft/vs-streamjsonrpc/blob/04ed5e6f608758b8f7ef6278107405149f9afa47/src/StreamJsonRpc/JsonRpcProxyOptions.cs#L48-L52

**Comment by mthgr** [comment]
Thanks!
