### ISSUE TITLE
IServer vs Server: Are they meant to be used together?

### ISSUE THREAD

**Issue by mthgr** [microsoft/vs-streamjsonrpc#426]
I'd like to know if this is a typical implementation:

```
jsonRpc.AddLocalRpcTarget(
    new Server(),
    new JsonRpcTargetOptions
    {
        AllowNonPublicInvocation = false,
    });

var server = jsonRpc.Attach<IServer>(jsonRpcProxyOptions);

jsonRpc.StartListening();

```
In the context of a client application, if I understand correctly IServer is used to describe methods that exist on the remote server and can be called by the application and the Server class is used to register local callbacks for notification received from the server for example?

The above code works but I'm not sure why I got the impression that I should be using one or the other by reading the documentation and that they are not meant to be used together.

Thanks.

**Comment by AArnott** [comment]
I don't know how you've defined `Server`, but if `Server` implements `IServer` then what you have _doesn't_ make sense.

The interface passed to `Attach<T>` is indeed the interface that describes what the remote party offers.
The object passed to `AddLocalRpcTarget` should have the methods that *you offer* to the remote party.
