### ISSUE TITLE
Support IAsyncEnumerable<T> prefetch without returning `Task<IAsyncEnumerable<T>>`

### ISSUE THREAD

**Issue by jdrobison** [microsoft/vs-streamjsonrpc#430]
The `.WithPrefetchAsync` extension returns `ValueTask<IAsyncEnumerable<T>>` which means an async enumerator method has to change its signature (or add an overload) in order to support prefetching.

Can we do better?

**Comment by AArnott** [comment]
I am going to try to add a prefetch setting to `JsonRpcEnumerableSettings` and then add the awaiting logic within StreamJsonRpc itself.
