### ISSUE TITLE
Provide order-preserving SynchronizationContext

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#440]
We document that order isn't preserving by default here: https://github.com/microsoft/vs-streamjsonrpc/blob/master/doc/resiliency.md#when-message-order-is-important, but we don't provide a `SynchronizationContext` that preserves order. 

We should do this, either from this repo or perhaps the vs-threading repo.

Thought should be given to whether it only preserves order for initial invocations or continuations as well (by applying itself as Current before invoking the delegate).

**Comment by CyrusNajmabadi** [comment]
> We should do this, either from this repo or perhaps the vs-threading repo.

Could is just be simpler here, and allow a simple bool that says order preservation is desired?  I can't imagine a case where i would want to think about passing a sync context to some other system.  It's just not the level of abstraction that makes sense for us.  

For example, in Roslyn, i don't believe we've ever had to make our sync context (though maybe we have one special one for tests).   Standard procedural logic and TPL + async/await semantics work fantastic and are what we want in the libraries we're using (esp. an RPC one).

**Comment by AArnott** [comment]
> allow a simple bool that says order preservation is desired?

That might be fine if we didn't already have an API to allow the user to set a `SynchronizationContext` on which to invoke every incoming RPC call. As we already have that API, adding another API that further changes how these things are scheduled would complicate the library and IMO the public API as well.
As long as it's still a one liner, I think it can be *almost* as simple as a boolean. Particularly if the API docs point directly at it. For example, it could be this:

```cs
jsonRpc.SynchronizationContext = JsonRpc.OrderPreservingSynchronizationContext;
```

Offering the `JsonRpc` the opportunity to set the `SynchronizationContext` is more powerful anyway, since it allows scheduling of the RPC methods to the main thread of an application for example. Or to be synchronized with any other code that might run for other reasons. A library can protect itself from unwanted concurrency between itself and RPC calls, for _any_ thread, simply by sharing its `SynchronizationContext` with the `JsonRpc` instance that it has invited to invoke methods on it.

**Comment by AArnott** [comment]
The vs-threading library already defines a `SingleThreadedSynchronizationContext`, so defining the `NonConcurrentSynchronizationContext` next to it makes the most sense, IMO. 
The vs-streamjsonrpc library already depends on vs-threading, so using types from there is fair game. We can document prominently that the `NonConcurrentSynchronizationContext` is the way to get order preservation when invoking RPC methods.
