### ISSUE TITLE
UseSingleObjectParameterDeserialization without adding a attribute to all methods

### ISSUE THREAD

**Issue by daniel-vetter** [microsoft/vs-streamjsonrpc#444]
Hi,

If i want to customize the name mapping between incoming calls and my target methods, i can pass a transform function to JsonRpcTargetOptions so i don't need to add a JsonRpcMethod attribute to all my methods. But if want to use the single object parameter deserialization for all my methods, there is no such option. Is there any way i can centralize this too?

Otherwise, would it be possible to add the UseSingleObjectParameterDeserialization feature to JsonRpcTargetOptions ?

**Comment by AArnott** [comment]
I'm glad to hear so many of our features are turning out useful to you.
What you're asking for makes a lot of sense.

Would you care to author the PR to add `bool JsonRpcTargetOptions.UseSingleObjectParameterDeserialization`?
