### ISSUE TITLE
Technique for waiting for work to complete?

### ISSUE THREAD

**Issue by jlorich** [microsoft/vs-streamjsonrpc#466]
Right now the `JsonRpc.Completion` task only continues on _disconnection_, not necessarily when all the tasks have been processed and completed (or even started).  Is there a means of knowing when the work is truly complete? On disconnection I'd like to wait to complete all the work before exiting / reporting back. 

I've tried multiple means of leveraging SynchronizationContexts but awaiting the `Completion` or a provided `SynchronizationContext` always continues on as soon as there's an await in the target method, and sometimes even before the target method even starts running.  Using a Single-threaded context proves to be problematic as well, as you can easily await the context after a message is read but _before_ it's actually dispatched to run, blocking it from doing anything.

What I actually want to achieve is routing RPC messages through IoT hub to Event Grid and then back down to the IoT device.  From the device side this works well - I've got a handler I can push received messages to and send messages with - but from the service side the function always exits before work is complete, which will cause problems down the road.

Maybe this just isn't the best choice of library for what I'd like to do right now, but it seems reasonable to need a want to waiting until all the work is complete.

**Comment by AArnott** [comment]
It's an interesting scenario, and I totally respect your goal of knowing when all work is done. We have a similar requirement in Visual Studio but I don't think we considered this particular application of it, so I appreciate you bringing it to my attention.

So to double-check I understand you: you want a Task that completes when the connection is closed and all *incoming* requests have completed or aborted, right? 

I mean, once the connection is over, no more work will be coming in, and any work that came in before but isn't done *might* be fruitless (depending on whether there are side effects on the server from those requests), but they are still running till they stop after all, and you want to know when *everything* is done, even if it's done after the connection is dropped.

Yes?

If so, I imagine we can come up with something.

**Comment by jlorich** [comment]
Yes, that exactly!

Azure Functions keeps track of a single method being executed, which in this case is receiving in the raw json-rpc messages from EventGrid.  If we arbitrarily spin off long running background work and _don't_ await them we're likely to have the Functions process killed before it's complete.

Another option would be to possibly open up the JsonRpc class a bit so it's usable outside of an IJsonRpcMessageHandler context.  On the client/device side I have a "stream" of data going in and out, but on the service side I typically receive one event and send one response - that's it.  Even just being able to call `DispatchIncomingRequestAsync` by hand could likely be sufficient.
