### ISSUE TITLE
Serialize exceptions with ISerializable pattern for error messages

### ISSUE THREAD

**Issue by AArnott** [microsoft/vs-streamjsonrpc#468]
We should consider serializing exceptions with `Exception.GetObjectData` and deserializing using the associated constructor. We would pass in a `SerializationInfo` object that we control rather than use .NET's binary formatter.
If we did this, we'd likely still throw `RemoteInvocationException` as we do now, but could supply the deserialized exception as the `InnerException`.

If we do this, our deserializer should follow all the rules described [here](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?view=netcore-3.1).

Tracked internally by https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1128351

**Comment by kzu** [comment]
Might also be worth exploring whether it would be useful to also serialize [Exception.Data](https://docs.microsoft.com/en-us/dotnet/api/system.exception.data?view=netcore-3.1) if present. Might not be used a lot, but in these remove scenarios, it could provide a mechanism to propagate custom data without having to create custom exception types and enabling the corresponding serialization for each...

**Comment by AArnott** [comment]
We recently used the Data dictionary ourselves in order to avoid a dependency on a new exception type.

**Comment by kzu** [comment]
ok, hacked-up spike looks promising and shows that this could indeed be quite valuable for the .NET clients: https://github.com/kzu/spikes/tree/master/jsonrpc-exceptions

**Comment by AArnott** [comment]
FWIW this should even be doable without changing StreamJsonRpc at all, since the methods involved are virtual.

**Comment by kzu** [comment]
Absolutely. But that would mean that services would *need* to inherit from some `JsonRpc`-derived base class that could give this to them for free. But maybe that's fine?

**Comment by AArnott** [comment]
Having it built-in is certainly an option. I wanted to call it out though that our extensibility model allows for such functionality without actually changing the library.

**Comment by AArnott** [comment]
Let's work #502 into this.

**Comment by AArnott** [comment]
After #505 this is pretty trivial. I have a prototype that I'm working into a shippable state.
