### ISSUE TITLE
Generated Proxy Disposal

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#477]
Are generated client proxy events delegates released for garbage collection when `Dispose` is called?

**Comment by AArnott** [comment]
It is not. The proxy internally calls `AddLocalRpcMethod` to wire up methods to receive 'events'. This `AddLocalRpcMethod` as well as the more common `AddLocalRpcTarget` are irreversible: they maintain strong references to their targets that are only released when the `JsonRpc` instance itself is released.

If you have a scenario where you need to create many proxies for the same RPC connection over time, such that this memory needs to be reclaimed without disposing the connection itself, let us know and we can consider supporting it.
