### ISSUE TITLE
Attribute to ignore methods from being proxied/invoked

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#485]
Similar to asp.net core's `[Ignored]` attribute, can this also be implemented for the dynamically generated proxies?
The use-case would be allowing invoke events via public methods on the server side; however, these methods should not be invoked by the client.

**Comment by AArnott** [comment]
The dynamic proxies are based on an interface. Can you omit these event raising methods from the interface?
If not, what would you propose the implementation do if called? Throw? As it is, I imagine it would attempt to invoke the method on the server, which would likely lead to the event being raised back on the client.
But by default only public methods are exposed to RPC, so if you make these methods internal or explicit interface implementations, I think the RPC on the server will reject the request and the client will end up throwing.

**Comment by vflame** [comment]
Thanks for the response. I'll play around with it but I suppose there's no harm in having the client invoke the event to itself since it wouldn't have any of the context/state that the server has to fire a "proper" event.
