### ISSUE TITLE
Race condition in InvokeWithCancellationAsync

### ISSUE THREAD

**Issue by tmat** [microsoft/vs-streamjsonrpc#489]
Cancellation of `JsonRpc.InvokeWithCancellationAsync` might result in error RemoteProtocolViolation: A response was received without a request having been sent.

Related VS Feedback issue: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1156256

Repro:

1) Install VS 16.7.0 Preview 4.0 [30312.25.d16.7] (or any 16.7 P4 build before 7/14).
2) Set `ServiceHubTraceLevel=All`
3) Clone https://github.com/dotnet/roslyn and open Roslyn.sln
4) Make some changes, use IDE features such as Go To Definition, Find all References, etc.
5) After a while (a few minutes) VS displays gold-bar reporting JSON RPC exception and asking to restart Roslyn's ServiceHub process.
5) ServiceHub log `*-ManagedLanguage.IDE.RemoteHostClient-*.log` contains something like:

```
07/14/2020 10:52:29 Pacific Standard Time: Information : 6 :Received request "3943" for method "ReportTodoCommentDataAsync".

07/14/2020 10:52:29 Pacific Standard Time: Critical : 13 :Connection closing (RemoteProtocolViolation: A response was received without a request having been sent.). 

07/14/2020 10:52:29 Pacific Standard Time: Information : 9 :Invoking Microsoft.VisualStudio.LanguageServices.Implementation.TodoComments.VisualStudioTodoCommentsService.ReportTodoCommentDataAsync(DocumentId, ImmutableArray`1, CancellationToken)
07/14/2020 10:52:29 Pacific Standard Time: Information : 8 :{"id":3943}
07/14/2020 10:52:29 Pacific Standard Time: Verbose : 8 :Sent: {
  "jsonrpc": "2.0",
  "id": 3943,
  "result": null
}

07/14/2020 10:52:29 Pacific Standard Time: Error : 3 : [devenv:30604] Stream disconnected unexpectedly:  RemoteProtocolViolation, 'A response was received without a request having been sent.', LastMessage: , Exception: 

07/14/2020 10:52:29 Pacific Standard Time: Error : 18 :Exception thrown while transmitting message: System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at StreamJsonRpc.MessageHandlerBase.<WriteAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<TransmitAsync>d__144.MoveNext()
```

A workaround has been implemented in Roslyn disabling the ability to cancel RPC invocations:
https://github.com/dotnet/roslyn/pull/45982

The issue has not occurred in a build with the workaround.

**Comment by AArnott** [comment]
The message in the error was introduced by f89ff0ba, which first showed up in StreamJsonRpc 2.5.26, and first seen in VS for 16.7-preview.4.
I'm investigating a hypothesis that @sharwell presented that may identify the race condition.

**Comment by AArnott** [comment]
I have a repro in a deterministic automated test that I wrote. The issue is that if cancellation happens between writing the message and flushing it, flushing will cancel, reporting the message transmission as failed. But in fact it's still sitting in the transmission queue waiting to go out. It will slip out with the next message's flush call. Since we didn't expect it to go out, we didn't track its request ID and were surprised when a response came back.

**Comment by AArnott** [comment]
Reactivating to track merge into v2.5 branch.
