### ISSUE TITLE
Releases/tags are missing

### ISSUE THREAD

**Issue by n9** [microsoft/vs-streamjsonrpc#497]
Nuget release notes points to non-existent releases/tags. See Release Notes section in https://www.nuget.org/packages/StreamJsonRpc.

**Comment by AArnott** [comment]
Quite right. Thanks for reporting. I've published the release notes for all but the last prerelease on nuget.org, and am working toward the last one too.

**Comment by AArnott** [comment]
I unlisted the 2.6.9-alpha release on nuget.org because it had nothing new over the 2.5 release.
