### ISSUE TITLE
Attach<T>

### ISSUE THREAD

**Issue by TonyValenti** [microsoft/vs-streamjsonrpc#515]
How do I:
Attach<TInterface>(Stream, TInstance) where TInstance : TInterface

?

**Comment by TonyValenti** [comment]
Github changed my formatting.  Here it is again:

````
Attach<TInterface>(Stream, TInstance) where TInstance : TInterface
````

**Comment by AArnott** [comment]
I don't understand your question? Are you trying to reference a particular, existing API and ask how to use it? Or are you asking what to do about an absence of an API?

There are many overloads of Attach. Some static, some not. You can learn about them here: https://docs.microsoft.com/en-us/dotnet/api/streamjsonrpc.jsonrpc.attach?view=streamjsonrpc-2.3#StreamJsonRpc_JsonRpc_Attach_System_IO_Stream_System_Object_
