### ISSUE TITLE
HeaderDelimitedMessageHandler may write only header but not the body when the request is cancelled

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vs-streamjsonrpc#55]
*Repro:*
Invoke a method on a server and then cancel the cancellation token passed to the method. Depending on your luck, the cancellation may happen so that the header is already written to the underlying stream [here](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs#L238), but the content is not, and it got cancelled [here](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs#L241). Sending another message on that JsonRPC makes it send the header and the content. The receiving end will get the header from the first (cancelled) message, and then the header and the content from the next message. It'll try to use the first header to read the whole message, and will read malformed json (it will contain the header and part of the body of the second message). Then it'll close the stream.

*Expected:*
Sending a JSON RPC message by the message handler should be atomic. We should write header and content together, or don't write anything at all.

**Comment by AArnott** [comment]
@ilyabiryukov VS 15.3 is equivalent to the existing v1.1 milestone. So I've moved to that one.
