### ISSUE TITLE
Feature request: support GZIP and DEFLATE content encoding

### ISSUE THREAD

**Issue by gdalsnes** [microsoft/vs-streamjsonrpc#562]
I see some other JSON-RPC clients support this (http://software.dzhuvinov.com/json-rpc-2.0-client.html, https://github.com/ybbus/jsonrpc/issues/18)
Nice to have:-)

**Comment by AArnott** [comment]
The two example you reference implement support directly for the HTTP protocol, where header-based support for compression makes sense. 
StreamJsonRpc does not come with (built-in) support for HTTP as a transport, but rather focuses on two parties that share a duplex Stream. In this scenario, Gzip/default _already_ works without special support from the library: just wrap your Stream in a GzipStream or DeflateStream before handing the wrapper to StreamJsonRpc. :)

**Comment by dennisvanderpool** [comment]
@AArnott Hi Andrew, I need this as well but have a hard time getting it to work properly. Can you send it me in the right direction with some sample code? Many thanks.

**Comment by AArnott** [comment]
@dennisvanderpool Are you asking for a sample of StreamJsonRpc over a compressing HTTP protocol, or a GzipStream sample?
