### ISSUE TITLE
Optimize allocations in AddLocalRpcMethod

### ISSUE THREAD

**Issue by tmat** [microsoft/vs-streamjsonrpc#575]
We see some allocations of `int[]` in Roslyn perf tests that would be good to remove:

Name | Inc % | Inc
-- | -- | --
`streamjsonrpc.ni!JsonRpc.AddLocalRpcMethod` | 3.0 | 2,680,744
` clr!JIT_New` | 1.2 | 1,068,888
`mscorlib.ni!System.Collections.Generic.Dictionary2[System.__Canon,System.__Canon].Insert(System.__Canon,   System.__Canon, Boolean)` | 1.1 | 965,736
`streamjsonrpc.ni!JsonRpc.TraceLocalMethodAdded` | 0.7 | 646,120

Link to internal RPS results:
http://aka.ms/BRAT?Form=BRAT&System=DTL&Locale=English&Runs=%25PerfDDRITs%25&Branch=main&Parent=main&FIBuild=30605.164&RIBuild=30605.164.vslsnap.201006.015741.279356&Private=False&GetResults=True&Since=10-01-2020

**Comment by AArnott** [comment]
Fixed by several recent PRs. Please test  2.7.37 or later when verifying this.
