### ISSUE TITLE
TypeNameHandling

### ISSUE THREAD

**Issue by TonyValenti** [microsoft/vs-streamjsonrpc#577]
Can you please enable discussions on this repo?

Also, how do I enable Newtonsoft's TypeNameHandling property?  i have methods that need to return a number of objects that derive from a common base type.

**Comment by AArnott** [comment]
I'm not familiar with this "discussions" setting you speak of. I don't see anything in the repo settings for it like I do for wiki, issues, etc. 
Our discussions happen over on gitter.im (see our README).

As for TypeNameHandling, you can do this by creating the `JsonMessageFormatter` yourself, which exposes API in which you can customize the JsonSerializer settings including that property.
Then you can pass that `JsonMessageFormatter` to the `HeaderDelimitedMessageHandler` constructor along with your stream, then pass that handler to the `JsonRpc` constructor and you're off the races. :)

**Comment by TonyValenti** [comment]
Hi @AArnott .  Thanks for the pointers.  I'm almost there.

RE Discussions:  Take a look at https://github.com/dotnet/csharplang/discussions and you'll see what I mean.

RE JsonMessageFormatter, below is a snippet of my code.  You'll notice the ```Legacy``` flag that toggles between my existing code and the code I'm writing to try to implement your input.

```
 public class NamedPipeProtocolProvider : IProtocolProvider {

           bool Legacy = true;

//When Hosting (the Server runs this)
            if (Legacy) {
                RPC = JsonRpc.Attach(Stream, Instance);
            } else {

                var Handler = CreateMessageHandler(Stream);

                RPC = new JsonRpc(Handler, Instance);
            }

            await RPC.Completion
                .DefaultAwait()
                ;

//When Connecting (the Client runs this)

           if (Legacy) {
                ret = StreamJsonRpc.JsonRpc.Attach<T>(Stream);
            } else {
                var Handler = CreateMessageHandler(Stream);

                ret = JsonRpc.Attach<T>(Handler);
            }

//Other Relevant Methods:
 protected virtual HeaderDelimitedMessageHandler CreateMessageHandler(Stream Stream) {
            var Formatter = new JsonMessageFormatter() {
                JsonSerializer = {
                    TypeNameHandling = Newtonsoft.Json.TypeNameHandling.Objects,
                }
            };

            var ret = new HeaderDelimitedMessageHandler(Stream, Formatter) {
                
            };

            return ret;
        }

}
```

When ```Legacy = true``` the code runs.
When ```Legacy = false``` it seems as though message invocations hang.

What am I missing?

**Comment by TonyValenti** [comment]
Looks like I was missing a:
```
RPC.StartListening();
```

I'm good now!

**Comment by AArnott** [comment]
It looks GitHub Discussions are [still in beta and not available for all repos](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions). That would explain why I can't turn it on here.
