### ISSUE TITLE
Cannot invoke a method that contains just the CancellationToken parameter

### ISSUE THREAD

**Issue by drognanar** [Microsoft/vs-streamjsonrpc#60]
I have a method with a following signature: `public void Method(CancellationToken token) => DoSomething();`.

I tried to invoke this method with cancellation and pass an empty parameter array. However, this results in an exception:

```
StreamJsonRpc.RemoteInvocationException: Parameter count mismatch.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__63`1.MoveNext()
   at 
```
After debugging this I noticed that `JsonRpcMessage.GetParameters` method returns an empty object array for parameters (instead of an array with one item left for the cancellation token) and as a result invoking the method throws the exception.

I also tried to pass null or the cancellation token as a parameter, but this failed the check that validates the parameter count in `TargetMethod.TryGetParameters` (`if (paramCount < method.RequiredParamCount || paramCount > method.TotalParamCountExcludingCancellationToken)`).

**Comment by IlyaBiryukov** [comment]
StreamJsonRpc handles cancellation token parameters differently - it allows to cancel the server method from the client. To invoke such a method, use [JsonRpc.InvokeWithCancellationAsync](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/JsonRpc.cs#L421) methods.

**Comment by drognanar** [comment]
I was already calling the `InvokeWithCancellationAsync` method. Here's the full sample with the server/client and the invocation that throws the exception:

```csharp
namespace JsonRPCIssue
{
    class Program
    {
        static void Main(string[] args)
        {
            var streams = Nerdbank.FullDuplexStream.CreateStreams();
            var serverRpc = JsonRpc.Attach(streams.Item1, new Server());
            var clientRpc = JsonRpc.Attach(streams.Item2);
            clientRpc.InvokeWithCancellationAsync(
                nameof(Server.CallWithCancellation),
                new object[0],
                CancellationToken.None).GetAwaiter().GetResult();
        }
    }

    class Server
    {
        public Task CallWithCancellation(CancellationToken token)
        {
            Console.WriteLine("Called");
            return Task.FromResult(true);
        }
    }
}
```

**Comment by AArnott** [comment]
I verified this bug repros in a unit test that I just added in beb61e5.
