### ISSUE TITLE
Unable to use interface as event argument with Union-attributed interface

### ISSUE THREAD

**Issue by dtivel** [microsoft/vs-streamjsonrpc#611]
Repro steps:
1. Clone [this fork](https://github.com/dtivel/vs-streamjsonrpc).
2. Switch to the [repro0](https://github.com/dtivel/vs-streamjsonrpc/tree/repro0) branch.
3. Open the solution in Visual Studio.
4. Debug test [Repro](https://github.com/dtivel/vs-streamjsonrpc/blob/repro0/test/StreamJsonRpc.Tests/MessagePackFormatterTests.cs#L350).

Result:  The following exception is thrown:
```
MessagePack.MessagePackSerializationException
  HResult=0x80131500
  Message=Unexpected msgpack code 129 (fixmap) encountered.
  Source=MessagePack
  StackTrace:
   at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
```
Observation:  if the test, server, and client all use the concrete type (`Fruit`) instead of the interface (`IFruit`), the test passes.  However, I want the concrete type to remain a private implementation detail.

**Comment by AArnott** [comment]
It's not valid to mix `Fruit` and `IFruit` types. The declared type must match on serializer and deserializer side in order for the msgpack binary representation to match.
