### ISSUE TITLE
2.6.121 pkg, wrong System.Collections.Immutable dependency?

### ISSUE THREAD

**Issue by gdalsnes** [microsoft/vs-streamjsonrpc#626]
nuspec has this:        <dependency id="System.Collections.Immutable" version="1.7.1" exclude="Build,Analyzers" />

The netstandard2.0 assembly reference is:
// Assembly Reference System.Collections.Immutable
Version: 1.2.5.0 
Name: System.Collections.Immutable, Version=1.2.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a 

1.2.5.0 is found in pkg System.Collections.Immutable version="1.7.0"

**Comment by gdalsnes** [comment]
Not a big deal as a binding redirect will fix it, but still think it was strange

**Comment by AArnott** [comment]
What version of the streamjsonrpc package are you looking at dependencies for? 

In our latest package version we depend on the System.Collections.Immutable v1.7.1 nuget package, which uses assembly version 1.2.5.0.  This matches the assembly version that StreamJsonRpc was compiled against.
