### ISSUE TITLE
CancellationToken no longer works on v2.6.121 when setting TypeNameHandling.Objects

### ISSUE THREAD

**Issue by rruizGit** [microsoft/vs-streamjsonrpc#630]
### Use Case:

- Using dynamic proxies.
- Using Cancellation Tokens.

A simple method implemented in the server as part of a unit test:

```C#
        public Task CancellableAsync(int secondsToDelay, CancellationToken cancellationToken)
        {
            return Task.Run(() =>
            {
                for (int i = 0; i < secondsToDelay; i++)
                {
                    Thread.Sleep(1000);
                    cancellationToken.ThrowIfCancellationRequested();
                }
            }, cancellationToken);
        }
```
Previous to v2.6.121, if we called this method through a Dynamic Proxy and provided a CancellationToken, cancelling the operation would cancel the token in this server method and the exception would be thrown.  With v2.6.121 the token is never cancelled in the server. I can see the cancellation message going throught the RPC. Not sure if this is a bug or if there is something new we have to do with the addition of ICancellationStrategy.

**Comment by AArnott** [comment]
This should work. No breaking change was intended. Can you send a full repro and/or include verbose logs from both parties in the minimal repro so I can investigate?

**Comment by rruizGit** [comment]
Andrew, 

Sorry it took me so long. Turns out it was not so easy to reproduce. I did eventually figure out what in our setup was causing the failure. In short, the failure only occurs in v2.6.121 **if** you are using the JsonMessageFormatter to format the JsonSerializer. We format ours this way:

```C#
    var serverFormatter = new JsonMessageFormatter(new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    serverFormatter.JsonSerializer.TypeNameHandling = TypeNameHandling.Objects;
    serverFormatter.JsonSerializer.TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple;
    var serverRpc = new JsonRpc(new HeaderDelimitedMessageHandler(serverStream, serverFormatter));
```

If _TypeNameHandling_ is set to _Objects_ or _All_ the CancellationToken workflow fails, but only on v2.6.121. If I revert to the previous release it works fine. When it fails, we see this in the log:

_Invocation of "$/cancelRequest" cannot occur because arguments do not match any registered target methods._

I have created a small VS project which demonstrates the problem. It can be found [here](https://1drv.ms/u/s!AoUSEZvDd2WAiJ1metS0r2pe0A6qFg?e=LJ01M5).

**Comment by AArnott** [comment]
Great. Your repro was excellent. Your customization of the TypeNameHandling settings is corrupting the cancelRequest call by adding a `$type` "parameter" to the method being invoked:

```json
{
  "jsonrpc": "2.0",
  "method": "$/cancelRequest",
  "params": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib",
    "id": 2
  }
}
```

This config would mess up other RPC calls too if you used the by-name approach too. From your repro, if I modify your dynamic proxy line to be:

```cs
            ICancellationTest dynamicCancellationTest = clientRpc.Attach<ICancellationTest>(new JsonRpcProxyOptions { ServerRequiresNamedArguments = true });
``

Then the original RPC call fails too with the same corruption:

```json
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "LongRunningTaskAsync",
  "params": {
    "$type": "_param_89860b9c-db21-4d36-bfe9-bc5c79a2d2e8, rpcProxies_d27a2976-4a31-41b5-b408-997a14787228",
    "secondsToDelay": 10
  }
}
```

I don't know why this is a recent regression. I'll have to see what StreamJsonRpc can do to resist Newtonsoft.Json injecting these properties into non-user objects.

**Comment by AArnott** [comment]
This bug appears to repro with  v2.5.46 as well. Can you confirm the version you were using before where the failure didn't occur?

**Comment by rruizGit** [comment]
With my repo project, if I simply switch to the v2.5.46 NuGet package I can see the Token being cancelled in the _LongRunningTaskAsync_ method and the _TaskCanceledException_ received on the calling side . I updated my project to trace all the messages. I can see the same message (see below), but it works.

```json
Server Verbose: 7 : Received: {
  "jsonrpc": "2.0",
  "method": "$/cancelRequest",
  "params": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib",
    "id": 2
  }
}
```

BTW, I did try the _Attach_ with the _JsonRpcProxyOptions_ you mentioned and it does fail with v2.5.46. 

[Here is an updated version of the project](https://1drv.ms/u/s!AoUSEZvDd2WAiJ1nVJKF2SLohuFl_Q?e=PQp8mF). **Note** that it is pointing at v2.5.46 and it works for me.

**Comment by rruizGit** [comment]
@AArnott, any idea when this issue will be addressed? I spent some time looking at it. In JsonMessageFormatter:ReadRequest() the code forks depending on the JToken type:

```C#
      JToken args = json["params"];
      object? arguments =
          args is JObject argsObject ? PartiallyParseNamedArguments(argsObject) :
          args is JArray argsArray ? (object)PartiallyParsePositionalArguments(argsArray) :
          null;
```
The way we tend to use StreamJsonRpc our own calls go through JArray, even when they have only one parameter. This works fine. But in the case of the _$/cancelRequest_ invoke, it calls _PartiallyParseNamedArguments()_. This just splits the "params" in
```json
  "params": {
    "$type": "System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[System.Object, mscorlib]], mscorlib",
    "id": 2
  }
```
into a dictionary, but it treats what should be one parameter with $type as two parameters.
Later... in _JsonRpcRequest:TryGetTypedArguments()_ the ArgumentCount check fails.

```C#
      // If we're given more arguments than parameters to hold them, that's a pretty good sign there's a method mismatch.
      if (parameters.Length < this.ArgumentCount)
      {
          return ArgumentMatchResult.ParameterArgumentCountMismatch;
      }
```
because _ArgumentCount_ is 2 when it should be one.
