### ISSUE TITLE
Connection with named pipes very slow

### ISSUE THREAD

**Issue by netcorefan1** [microsoft/vs-streamjsonrpc#632]
Hello,
I noticed a very long slowdown with Named Pipes using the official sample:

https://user-images.githubusercontent.com/63934725/104792782-f4002980-579f-11eb-9c55-34bbd470b34c.mp4

As you can see, the connection itself is fast, but when I call for the first time the method "GetAllIngredientsAsync()", it takes one second to return the result (sometimes even more). Subsequent calls return instantly. You're seeing release, in debug mode it's even worse, I have to wait a couple of seconds, the time required from VS to load the required modules. I initially thought it was due to the lazy loading of the referenced modules, but when I tried to load all references in advance I noticed that the slowdown still persist and the culprit is the loading of "Anonymously Hosted DynamicMethods Assembly".
For a long session it doesn't matter, but when I need to quickly open a process, execute a method and close, then it could be a problem.
Is this normal or I am missing something obvious? If I remain connected and request another instance of the interface, did I will have to go to the same slowdown?

I may be wrong, but this library seems to add a great amount of overhead. There is an unmaintained [fork](https://github.com/shana/StreamRPC) which minimize dependencies, but I experienced the same of the above. 
Are there future plans to reduce dependencies and make the library lighter?
Thanks

**Comment by AArnott** [comment]
@netcorefan1 Nothing prevents you from commenting on a closed issue. We will re-open the issue if an ongoing discussion merits it. Please do not open redundant issues.

**Comment by netcorefan1** [comment]
I am very sorry for that. I opened a new issue because effectively I was going to report a different issue, but I mixed some parts of the two and could seem redundant issues. I am going to do some editing in order to make the issues distinct, unrelated and clear.
Thanks

**Comment by netcorefan1** [comment]
https://github.com/microsoft/vs-streamjsonrpc/issues/629#issuecomment-760623931
@AArnott commented 22 hours ago
The main reason I wanted to try shared memory is because I noticed a very long slowdown using Named Pipes using the official sample

@netcorefan1: Of everything that is going on during an RPC call, I'm curious how you determined that named pipes was the cause of the slowdown.

@AArnott Trying shared memory was already on my road map. The slowness experienced made me trying the memory mapped files sooner to see the difference. I have not determined that named pipes was the cause of the slowdown and instead of checking everything that is going on during an RPC call, I have done something simpler and easy: identify the specific module that is involved in the call and it is "Anonymously Hosted DynamicMethods Assembly" which get loaded on the first method call (see above). This module takes 1/2 seconds to load and the method only return after it finished to load. I am not sure if this is normal or I missed some configurations.

**Comment by netcorefan1** [comment]
I am afraid this has to do with dynamic code generation at runtime (as previously stated). Warming up has very little (and hardly noticeable) impact. I didn't experience this issue with similar libraries that does not rely on dcg (a sample is [grpc-dotnet-namedpipes](https://github.com/cyanfish/grpc-dotnet-namedpipes)).
As of now, the only workaround I saw in other [RPC](https://github.com/SciTechSoftware/SciTech.Rpc#performance) libraries is running a tool which will pre-generate the necessary assemblies. May be your stuff can manage to find a better way, I don't know.
Anyway, I am not sure if this should be reported as a bug since it is supposed to work in this way.

**Comment by AArnott** [comment]
Great, I'm glad you found the real cause of the perf difference.
You can avoid the dynamic code gen by simply instantiating JsonRpc and calling InvokeAsync yourself.
And yes, we may in the future utilize roslyn source generators to move the warmup perf hit to compile time.
