### ISSUE TITLE
Usage mismatch between AddTarget<T> and Attach<T> when using interface inheritance.

### ISSUE THREAD

**Issue by rruizGit** [microsoft/vs-streamjsonrpc#637]
Note that this is not necessarily a bug but pointing out a disconnect between AddTarget and Attach when using types (e.g. dynamic proxies). The ability to limit publishing to a specified type was added in v2.6.121.

If I define two interfaces, where one inherits the other:

```c#
    public interface IParentInterface : IChildInterface
    {
        Task<bool> MethodInParent();
    }

    public interface IChildInterface
    {
        Task<int> MethodInChild();
    }
```
I then implement the interfaces with a test class.
```C#
    public class TestClass : IParentInterface
    {
        public Task<bool> MethodInParent() => Task.Run(() => true);

        public Task<int> MethodInChild() => Task.Run(() => 42);
    }
```
I then publish the the test class object using the interface as the "exposingMembersOn" type:
```C#
       serverRpc.AddLocalRpcTarget<IParentInterface>(testClass, null);
```
And extract a dynamic proxy on the client side like this:
```C#
       IParentInterface proxy = clientRpc.Attach<IParentInterface>();
```
The dynamic proxy will include the method _MethodInChild()_ but will throw a _RemoteMethodNotFoundException_. This is because the publishing did not automatically publish the child interface, while the dynamic proxy implemented the parent and child interfaces. 

There is a workaround where you also publish the child:
```C#
      serverRpc.AddLocalRpcTarget<IParentInterface>(testClass, null);
      serverRpc.AddLocalRpcTarget<IChildInterface>(testClass, null);
```
and it works, but it seems like a disconnect in behavior. Personally, I think if I publish an interface, it should also publish any interfaces it inherits from, since that is what you get with the dynamic proxy. Or, possibly add a new option to _JsonRpcTargetOptions_ to trigger this behavior.

**Comment by AArnott** [comment]
Your parent and child names seem reversed, as `IParentInterface` is in fact a derivate of `IChildInterface`.

I agree though: `AddLocalRpcTarget<T>` should honor members of base interfaces as well.

**Comment by rruizGit** [comment]
True and not the first to point that out. I've confused my teammates before. My brain sees to reverse terms when looking at interfaces. :)
