### ISSUE TITLE
High number of dependencies (and some are questionable wrt portability)

### ISSUE THREAD

**Issue by knocte** [microsoft/vs-streamjsonrpc#639]
StreamJsonRpc's nuget package description starts with "A **cross-platform** .NETStandard library that implements...", however, when adding this dependency to a project, many many many sub-dependencies (dependencies of StreamJsonRpc) are added, and among those there are what seems to be Windows-only specific ones. E.g.:

- System.Security.AccessControl
- System.Security.Principal.Windows
- Microsoft.Win32.Registry
- Microsoft.Win32.Primitives

Is there any chance that the dependencies can be reviewed? Maybe split the nuget package in two, one truly cross-platform and the other one Windows-specific?

**Comment by AArnott** [comment]
The library is indeed cross-platform. The dependencies you list here are transitive dependencies and are only used when on Windows, for scenarios that probably do not even apply to StreamJsonRpc. But the direct dependencies are in fact used. Our tests run on all 3 major operating systems on .NET Core, as well as .NET Framework on Windows and even mono on mac+linux. This test runs reflect our commitment to ensure this library operates fully on all platforms.
