### ISSUE TITLE
Provide UserState to keep Data from JsonRpcRequest to JsonRpcResult 

### ISSUE THREAD

**Issue by pandaGaume** [microsoft/vs-streamjsonrpc#646]
When implement a custom MessageHandler, It's sometine necessary to save data to the generated JsonRpcRequest to make them available into the JsonRpcResult.
The following example is to deal with topics within MQTT Transport layer.
```...    
        protected override async ValueTask<JsonRpcMessage> ReadCoreAsync(CancellationToken cancellationToken)
        {
            do
            {
                if (_incomingQueue.TryDequeue(out MqttPublishEvent e)) 
                {
                    _hasRooms.Release();
                    var request= e.Payload.Length > 0 ? this.Formatter.Deserialize(new ReadOnlySequence<byte>(e.Payload)) : null ;
                    request?.UserState = e.Topic;
                    return request;
                }
                await _hasItems.WaitAsync();
            } while(true);
        }

        protected override async ValueTask WriteCoreAsync(JsonRpcMessage response, CancellationToken cancellationToken)
        {
            .... blabla ....
            // publish the data
            await Client.TryPublishAsync(response?.UserState , target.WrittenMemory, MqttQOS.AtLeastOnce);
        }
...
```
Alternatively you may allow the RequestId struct to carry the UserData and it's lead with less modification, but introduce kind of misuage of RequestId.
Any way, i can propose a PR on the subject if you're fine with.

**Comment by AArnott** [comment]
Are you asking for an additional property that isn't in the JSON-RPC spec to propagate from the request to the response?

We would not support building this into the request ID as a structured object since the spec requires that the request id be either a string or a number. Of course if you choose you can serialize whatever you want to make a string-based request id that has all the extra data you need. 

I'm not familiar with MQTT, but I wonder why the server needs to carry state on behalf of the client. Why can't the client just remember it directly based on a table of request id's?

**Comment by pandaGaume** [comment]
Thanks for the answer.
NO, i do not asking to change the spec :-).  Just to add a local property for local purpose ONLY which will be propagate after and up to the serialization (not included).
We can not relay on the id. 
for IOT devices connected to a broker scenario, it's about Many device to One Service and when the underlying transport is pub/sub, we loose one-one connection context and then we CAN NOT garanty the uniqueness of the ID. If we enforce an id pattern, we also exit from the spec. 

Imagine we have 2 devices A and B communicate with a service C
```
dummytopic/../A/C
dummytopic/../B/C
```
both with this payload
`{"jsonrpc": "2.0", "method": "GetHourlySpotPricing", "params": ["FR", "regulated","",17,"2021-02-26T18:21:00.511Z"], "id": "1"}
`
When reaching the point of WriteCoreAsync, we loose the context of who call and do not know if we might respond to A or C because the id's are equals

One trick is to change the id on the fly (decorate with some additional local user data) but to do so, we way need to 
1 - manipulate the id string to insert info in it which is feasible, but it's a way ugly hack
2 - change the id from struct to class/interface to allow inheritance/implementation

Easiest is to decorate the local message.
 
I made the change into a [fork](https://github.com/pandaGaume/vs-streamjsonrpc), you may have a look under this [branch](https://github.com/pandaGaume/vs-streamjsonrpc/tree/Add-Local-UserState-to-Message)

Regards

**Comment by AArnott** [comment]
Your "another solution" already exists, but the factory for instantiating the `JsonRpcMessage` classes lies in the `IJsonRpcMessageFormatter` implementation (which is extensible), so you'd have to provide your own formatter, which is non-trivial. Formatters tend to need their own private derivatives of the public classes, so exposing a new factory pattern would be incompatible with our existing requirements.

So back to your scenario: whatever device that is merging requests from two connections onto one single JSON-RPC server is violating the JSON-RPC spec, which requires the ID to be unique. The server should never see the same ID twice. I don't know how storing an extra field on the message on the server-side would help you. Are you perhaps writing the code to handle multiple incoming request streams into the handler itself?

We have a perhaps similar scenario in a couple of our applications, and the way we solve it is we have a middle-party that manages the many client connections to merge them into one JSON-RPC connection that goes to the singleton server. In the process, this middle-party _assigns a new request ID_ to each incoming request, and stores that ID in a table along with a record of which client it came from and what the original request ID was. Then when the response comes back from the server, the middle-party can look it up in the table, rewrite the request ID back to its original and forward the response onto the correct client. This has the advantage of following the protocol at every junction, and no special software on the RPC server is required. Would that work for you?

Another option, and what we _usually_ do is just have multiple instances of the RPC server: one for each client. If there is shared state across all those connections, that's fine--just initialize your RPC target objects with a reference to that shared state, or even use the same target object for all the RPC connections.

**Comment by pandaGaume** [comment]
Thank's for the answer and time. And also many thank's for the library.
G.
