### ISSUE TITLE
Allow server to specify data object in error result messages

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-streamjsonrpc#65]
We should define an Exception-derived type (that includes an object property) that the RPC server method can throw in order to specify the `JToken` (`JValue` or `JObject`) for the `data` field in the JSON-RPC error result message.

Today, we always [create a data object with the stack and code fields in it](https://github.com/Microsoft/vs-streamjsonrpc/blob/ce4d9894e7d5cefb180cf2d74c9c7905d4cbec4c/src/StreamJsonRpc/JsonRpc.cs#L843). 

By request from @tinaschrepfer

**Comment by tinaschrepfer** [comment]
It would be great if the caller can specify custom values for all 3 fields: error.code, error.message, error.data.  I can see the language server protocol specifying custom values for each field for certain scenarios.

**Comment by AArnott** [comment]
The `message` and `code` fields are already within the control of the server method that throws the exception (by setting `Exception.Message` and `Exception.HResult`). However, the `code` field can only be an integer. So we'd want to expand that to be a string as well.
