### ISSUE TITLE
Is it necessary to return an acknowledgement after an invocation? Or does the library ensure delivery / throw an exception on failure?

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#718]
```c#
public interface IInvocable
{
    Task<Message> OnDeliver(Message message);
    Task OnDeliver(Message message);
}

//implementation:
jsonProxy.OnDeliver(message);

message.Acknowledged= true;
return message;
```

Are both methods equivalent in terms of determining whether or not a message was successfully delivered? Or does the client initiating the call need to to confirm that the 'acknowledged' message was returned? Would like to avoid chattiness if jsonrpc already handles the acknowledgement receipt of a message.

**Comment by AArnott** [comment]
JSON-RPC supports request-response as well as notify (one-way). 
The proxy you generate always sends requests, meaning that the Task you get back completes only when the server acknowledges the server method completed. An exception thrown from the server (whether from the RPC method or before if the method couldn't be found) will be rethrown on the client when you await that Task.

**Comment by AArnott** [comment]
Also: the server gets a copy of the `Message`, so any changes it makes to it are *not* propagated back to the client unless the server returns the changed Message back to the client.

**Comment by vflame** [comment]
> Also: the server gets a copy of the `Message`, so any changes it makes to it are _not_ propagated back to the client unless the server returns the changed Message back to the client.

That makes sense. This is why I had the mutated Message object sent back , but it is unnecessary given that sends always complete or throw (connection/remote exception, etc.).
