### ISSUE TITLE
Add support for receiving events that do not conform to `EventHandler`/`EventHandle<T>` type

### ISSUE THREAD

**Issue by Tianfei-Wang** [microsoft/vs-streamjsonrpc#807]
The EventReceiver in RpcTargetInfo is not “fit” for event delegation,  whether to consider adding support for it recently.

**Comment by AArnott** [comment]
I don't understand what you're reporting. The `RpcTargetInfo` type is internal. Can you state your unmet requirement in terms of public API?

**Comment by Tianfei-Wang** [comment]
When I try to call a custom delegated event between two processes, StreanJsonRpc reports that event delegation is not supported (only EventHandler is supported), it says in the comment on line 736 of the StreamJsonRpc source code https://github.com/microsoft/vs-streamjsonrpc/blob/main/src/StreamJsonRpc/Reflection/RpcTargetInfo.cs

I need to use custom delegate in StreamJsonRpc how should it be done?

**Comment by Tianfei-Wang** [comment]
Glad you understood, but...
Reply to you:
1. Yes, I use the interface proxy. Actually, I switched from Net Remoting to StreamJsonRpc, because Net6 does not support Remoting. But there are no events inside my interface.
2.  our code is already similar and it doesn't work, below you can see some code samples
3. The implementation of JsonRpc is in the communication link layer (dll), and the method class MyReceiver is in the application layer (exe), I use Json.Attach(NetworkStreamStream stream, IMyInterface MyInterface); Can I achieve the same effect?

More info hopefully useful：
Background:
My StreamJsonRpc based on Tcp, implements the interface IMyInterface on the server and client
IMyInterface:
`public interface IMyInterface
    {
        Task<int> MyOddEvent(Param1 args1);
    }`

On sender <**do not**> use
`jsonRpc.InvokeAsync<IMyInterface>("MyOddEvent", "args1");//The reason for not using is that calling in string form can lead to naming errors.`
Instead, implement the interface on the sender and call the receiver's method through the interface instance (just like a local call, similar to Remoting), as follows:
`public class MySenderImpl
public IMyInterface MyInterface；

public CallReceiver(Param1 args)
{
MyInterface.MyOddEvent（args1）；
}`

The receiver code is slightly different with you, as follows:
`class MyReceiver: IMyInterface
{
public delegate void MyOddEvent(Param1 args1);
 public event MyOddEvent OddEvent;

public void MyOddEvent(Param1 arg1) // The method name is constrained by IMyInterface and is called directly on the sender side, with only one parameter
   {
      OddEvent.DynamicInvoke(args1); //Event subscription implements event response in the main program.
   }
}`

Do you have any suggestion for the above information? I'm replacing all my custom delegates with EventHandler<Args> now, but it always asks to pass two arguments (including sender and args1) when I only need one, which is boring.

**Comment by Tianfei-Wang** [comment]
Glad you understood, but...
Reply to you:

1、Yes, I use the interface proxy. Actually, I switched from Net Remoting to StreamJsonRpc, because Net6 does not support Remoting. But there are no events inside my interface.
2、our code is already similar and it doesn't work, below you can see some code samples
3、The implementation of JsonRpc is in the communication link layer (dll), and the method class MyReceiver is in the application layer (exe), I use Json.Attach(NetworkStreamStream stream, IMyInterface MyInterface); Can I achieve the same effect?

More info hopefully useful：
Background:
My StreamJsonRpc based on Tcp, implements the interface IMyInterface on the server and client
IMyInterface:
`public interface IMyInterface { Task<int> MyOddEvent(Param1 args1); }`
On sender <**do not**> use
`jsonRpc.InvokeAsync<IMyInterface>("MyOddEvent", "args1");//The reason for not using is that calling in string form can lead to naming errors.`
Instead, implement the interface on the sender and call the receiver's method through the interface instance (just like a local call, similar to Remoting), as follows:
`public class MySenderImpl
public IMyInterface MyInterface；

public CallReceiver(Param1 args)
{
MyInterface.MyOddEvent（args1）；
}`
The receiver code is slightly different with you, as follows:
`class MyReceiver: IMyInterface
{
public delegate void MyOwnDelegateType(Param1 args1);
public event MyOwnDelegateType OddEvent;

public void MyOddEvent(Param1 arg1) // The method name is constrained by IMyInterface and is called directly on the sender side, with only one parameter
{
OddEvent.DynamicInvoke(args1); //Event subscription implements event response in the main program.
}
}`
Do you have any suggestion for the above information? I'm replacing all my custom delegates with EventHandler now, but it always asks to pass two arguments (including sender and args1) when I only need one, which is boring.

**Comment by Tianfei-Wang** [comment]
‘’‘C#
class MyReceiver: IMyInterface
{
public delegate void MyOwnDelegateType(Param1 args1);
public event MyOwnDelegateType OddEvent;

public void MyOddEvent(Param1 arg1) // The method name is constrained by IMyInterface and is called directly on the sender side, with only one parameter
{
OddEvent.DynamicInvoke(args1); //Event subscription implements event response in the main program.
}
}
’‘’

**Comment by Tianfei-Wang** [comment]
‘’‘class MyReceiver: IMyInterface
{
public delegate void MyOwnDelegateType(Param1 args1);
public event MyOwnDelegateType OddEvent;

public void MyOddEvent(Param1 arg1) // The method name is constrained by IMyInterface and is called directly on the sender side, with only one parameter
{
OddEvent.DynamicInvoke(args1); //Event subscription implements event response in the main program.
}
}’

**Comment by Tianfei-Wang** [comment]
Glad you understood, but...
Reply to you:

1. Yes, I use the interface proxy. Actually, I switched from Net Remoting to StreamJsonRpc, because Net6 does not support Remoting. But there are no events inside my interface.
2. our code is already similar and it doesn't work, below you can see some code samples
3. The implementation of JsonRpc is in the communication link layer (dll), and the method class MyReceiver is in the application layer (exe), I use 
```C#
JsonRpc.Attach(NetworkStreamStream stream, IMyInterface MyInterface);
```
 Can I achieve the same effect?

More info hopefully useful：
Background:
My StreamJsonRpc based on Tcp, implements the interface IMyInterface on the sender and receiver
IMyInterface:
```C#
public interface IMyInterface 
{
 Task<int> MyOddEvent(Param1 args1);
 }
```
On sender **do not** use
```C#
jsonRpc.InvokeAsync<IMyInterface>("MyOddEvent", "args1");//The reason for not using is that calling in string form can lead to naming errors.
```
Instead, implement the interface on the sender and call the receiver's method through the interface instance (just like a local call, similar to Remoting), as follows:
```C#
public class MySenderImpl
{
public IMyInterface MyInterface；

public CallReceiver(Param1 args1)
{
MyInterface.MyOddEvent（args1）；//Directly call the receiver to implement the method name of the interface
}
}
```
The receiver code is slightly different with you, as follows:
```C#
class MyReceiver: IMyInterface
{
public delegate void MyOwnDelegateType(Param1 args1);
public event MyOwnDelegateType OddEvent;

public Task<int> MyOddEvent(Param1 args1) // The method name is constrained by IMyInterface and is called directly on the sender side, with only one parameter
{
//The actual problem occurs here, RpcTargetInfo can only handle events of the EventHandler class
OddEvent.DynamicInvoke(args1); //Event subscription implements event response in the main program.
return Task.FromResult(0);//actually don't care
}
}
```

Do you have any suggestion for the above information? I'm replacing all my custom delegates with EventHandler now, but it always asks to pass two arguments (including sender and args1) when I only need one, which is boring.

**Comment by AArnott** [comment]
Ok, your event actually returns a value, which makes it not an event at all by StreamJsonRpc use. Events are considered to be notifications in JSON-RPC, which not only have no return value, but if they were to throw an exception, the event raiser would never hear about that either. In your case, `MyOddEvent` returns an `int`, so that totally kicks "events" out of the picture. So... how do we solve this? Not too hard:

```cs
public interface Party1
{
    Task SomeMethodAsync();
}

public interface Party2
{
    Task<int> MyOddEvent(Param1 args1);
}
```

This is where JSON-RPC's peer-to-peer nature shines. Each end of the communication will implement one of these interfaces. This means "party 1" can invoke party 2's "MyOddEvent" method and await the result. 

You already know how to set up a JsonRpc connection on both ends. So far though, you may only be attaching an RPC target object on one end (party 1), and generating a proxy on the other end (party 2). But try doing the opposite as well: add a local RPC target on the party 2 side and generate a Party2 proxy for party 1's use.

**Comment by Tianfei-Wang** [comment]
en...maybe I can't express clearly, sorry
We seem to be getting farther and farther. Regarding the return value Task<int>, we don't actually need it (don't need to wait for the return of the other process). Sorry for the interference, I will delete it now.

I have implemented the local Obj of JsonRpc and the Proxy of the other party in the two processes respectively, but I can only use EventHandler for message transmission. I upload it to https://github.com/Tianfei-Wang/StreamJsonRpcTcp.git
Can you take a look at it for me? Exe2 to Exe1 use EventHandler to send message successfully, but I have to use custom delegate, i.e. message from Exe1 to Exe2 always throw exception from StreamJsonRpc is not supported.

**Comment by AArnott** [comment]
Thanks for the sample. Here's the fix: https://github.com/Tianfei-Wang/StreamJsonRpcTcp/pull/1
