### ISSUE TITLE
Multiple concurrent requests are handled one by one in newest version.

### ISSUE THREAD

**Issue by SummerZW** [microsoft/vs-streamjsonrpc#826]
# Problem
As [document](https://github.com/microsoft/vs-streamjsonrpc/blob/main/doc/resiliency.md) mentions, StreamJsonRpc can process another request when it still has one request processing. In version 2.5.46(the version in sample code), it works fine. However, in latest version 2.11.35, it works differently, which handles requests one by one. I have checked the issues list but didn't find anything related. Not sure it is a bug in latest version. Or it is an expected change when upgrading. If so, how should I make change to fix the behavior?

# Experiment
When client send two requests: Add and Minus. Here is the result and my code from sample code is attached.

Client StreamJsonRpc version is 2.5.46. When server StreamJsonRpc version is 2.5.46, the output in server is:
Received request: 1 + 2
Received request: 1 - 2
Calculate: 1 - 2
Calculate: 1 + 2
which means, when server is processing Add, it can receive the request of minus.

However, when server StreamJsonRpc version is 2.11.35, the output in server is:
Received request: 1 + 2
Calculate: 1 + 2
Received request: 1 - 2
Calculate: 1 - 2
which means, after processing Add is done, server start to receive the request of minus and process it.

# Code
In Server side, the entry `Program` and server logic in `InternalServer`.
```cs
class Program
{
    static async Task<int> Main(string[] args)
    {
        await NamedPipeServerAsync();
        return 0;
    }

    private static async Task NamedPipeServerAsync()
    {
        var stream = new NamedPipeServerStream("StreamJsonRpcSamplePipe", PipeDirection.InOut, 1, PipeTransmissionMode.Byte, PipeOptions.Asynchronous);
        await stream.WaitForConnectionAsync();
        var jsonRpc = JsonRpc.Attach(stream, new InternalServer());
        await jsonRpc.Completion;
    }

}

internal class InternalServer
{
    [JsonRpcMethod("AddAsync")]
    public int Add(int a, int b)
    {
        Console.Error.WriteLine($"Received request: {a} + {b}");
        Thread.Sleep(1000000);
        Console.Error.WriteLine($"Calculate: {a} + {b}");
        return a + b;
    }

    [JsonRpcMethod("MinusAsync")]
    public int Minus(int a, int b)
    {
        Console.Error.WriteLine($"Received request: {a} - {b}");
        Thread.Sleep(1000000);
        Console.Error.WriteLine($"Calculate: {a} - {b}");
        return a - b;
    }
}
```

I define an interface between client and server.
```cs
    public interface IAsyncServer
    {
        Task<int> AddAsync(int a, int b);
        Task<int> MinusAsync(int a, int b);
    }
```

In client side, I invoke Add and minus sequentially.
```cs
class Client
{
    static async Task Main()
    {
        var psi = new ProcessStartInfo(FindPathToServer());
        Process.Start(psi);
        Console.WriteLine("Connecting to server...");
        using (var stream = new NamedPipeClientStream(".", "StreamJsonRpcSamplePipe", PipeDirection.InOut, PipeOptions.Asynchronous))
        {
            await stream.ConnectAsync();
            Console.WriteLine("Connected. Sending request...");
            using (var jsonRpc = JsonRpc.Attach(stream))
            {
                IAsyncServer server = jsonRpc.Attach<IAsyncServer>();
                server.AddAsync(1, 2);
                server.MinusAsync(1, 2);
                Thread.Sleep(500000);
            }
            Console.WriteLine("Terminating stream...");
        }
    }

    private static string FindPathToServer()
    {
#if DEBUG
        const string Config = "Debug";
#else
        const string Config = "Release";
#endif
        return Path.Combine(
            Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),
            $@"..\..\..\..\StreamJsonRpc.Sample.Server\bin\{Config}\net472\StreamJsonRpc.Sample.Server.exe");
    }
}
```

**Comment by SummerZW** [comment]
This issue starts with 2.6.121 and 2.5.46 works fine.

**Comment by AArnott** [comment]
This is surprising to see. As one workaround while you wait for this issue to be reviewed, using `await Task.Delay` instead of `Thread.Sleep` in your RPC server methods ought to get them running concurrently.

**Comment by SummerZW** [comment]
Thanks for your help. We will use 2.5.46 temporarily. Hope your good news~
