### ISSUE TITLE
TypeLoadException when upgrading to dotnet 7 rc 2

### ISSUE THREAD

**Issue by nojaf** [microsoft/vs-streamjsonrpc#856]
Hello, 

When updating our SDK to `7.0.100-rc.2.22477.23` we got

```
  Error Message:
   System.AggregateException : One or more errors occurred. (Error writing JSON RPC Message: TypeLoadException: Could not load type 'System.Runtime.Compi
lerServices.IsReadOnlyAttribute' from assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.)
  ----> Newtonsoft.Json.JsonSerializationException : Error writing JSON RPC Message: TypeLoadException: Could not load type 'System.Runtime.CompilerServi
ces.IsReadOnlyAttribute' from assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
  ----> System.TypeLoadException : Could not load type 'System.Runtime.CompilerServices.IsReadOnlyAttribute' from assembly 'System.Collections.Immutable,
 Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

It occurred when we are calling:
```fsharp
let client = new JsonRpc(clientStream, clientStream)
client.StartListening()
```

does this ring a bell by any chance? Updating our project to `net7` does not make any difference.

**Comment by AArnott** [comment]
You're saying that updating your *sdk* version hits this, while still targeting something like net6 or earlier? That sounds like an SDK bug to me.

**Comment by nojaf** [comment]
Hello, I was able to extract a sample to easily reproduce the problem: https://github.com/nojaf/streamjsonrpc-repro

There is something going wrong when a struct needs to be serialized with the new SDK or runtime.
I'm quite confused why this is happening all of a sudden. Are `struct`s supported in this library?

**Comment by nojaf** [comment]
Turns out to be a problem in the F# compiler: https://github.com/dotnet/fsharp/issues/14275.
Nothing left to do here.
