### ISSUE TITLE
Array field data is lost when JsonRpc passes (DynamicInvoke) parameters

### ISSUE THREAD

**Issue by Tianfei-Wang** [microsoft/vs-streamjsonrpc#859]
Hi，When I use StreamJsonRpc to pass a Args (including an array field) between two processes, the array field data is lost after the parameter reaches the receiving process, and the test program is in (the test needs to start two processes): https://github.com/Tianfei-Wang/StreamJsonRpcTcp.git
when clicking the Send button of Exe1(Server), the parameter TestArgs is not passed to Exe2(Client), while the other parameters are normal.
I set breakpoints in `Exe2Event.DynamicInvoke(args);`  of Exe2Obj to look, before DynamicInvoke(args) the array carried data, but the array data was lost in the event response method Show in the Exe2 program.
How should I pass the array params object[] using StreamJsonRpc?

**Comment by Tianfei-Wang** [comment]
The problem occurs in the following connections in StreamJsonRpc:
https://github.com/microsoft/vs-streamjsonrpc/blob/main/src/StreamJsonRpc/JsonMessageFormatter.cs#:~:text=value%20%3D%20token%3F.ToObject(typeHint!%2C%20this.formatter.JsonSerializer)%3B
, or a reference problem (in Newtonsoft. json).？
JToken.ToObject cannot process the array parameter<Parameters>in the following JToken
{{
"Args1": 1,
"Args2": 2,
"Parameters": [
"8"
]
}}

There should be a better processing method or the array should be classified？@AArnott

**Comment by AArnott** [comment]
It works fine if you make this change:

```diff
-        public Exe2Args( int args1, int args2,params object[] alarmParameters)
+        public Exe2Args( int args1, int args2,params object[] parameters)
```

I suspect you'll find the same problem if you just try round-tripping the Exe2Args type through Newtonsoft.Json. The problem is you have no default constructor, and the constructor you _do_ have uses parameter names where 1 of the 3 do not match the field name, so newtonsoft.json doesn't know what to put there, and leaves it at its default value.
