### ISSUE TITLE
Attempted to access an element as a type incompatible with the array.

### ISSUE THREAD

**Issue by n9** [microsoft/vs-streamjsonrpc#860]
Version: 2.12.27 (current in nuget, but not as a release in this repo)
Caller: .NET 6 (Windows)
Target: .NET 6 (Android)

Exception: `StreamJsonRpc.RemoteInvocationException`
ErrorCode: -32000 (`StreamJsonRpc.Protocol.JsonRpcErrorCode.InvocationError`)
ErrorData.TypeName: `System.ArrayTypeMismatchException`
ErrorData.Message: Attempted to access an element as a type incompatible with the array.
ErrorData.Stack:
```
   at StreamJsonRpc.TargetMethod.TryGetArguments(JsonRpcRequest request, MethodSignature method, Span`1 arguments)
   at StreamJsonRpc.TargetMethod..ctor(JsonRpcRequest request, List`1 candidateMethodTargets, SynchronizationContext fallbackSynchronizationContext)
   at StreamJsonRpc.Reflection.RpcTargetInfo.TryGetTargetMethod(JsonRpcRequest request, TargetMethod& targetMethod)
   at StreamJsonRpc.JsonRpc.DispatchIncomingRequestAsync(JsonRpcRequest request)
```

Signature of the called method:

```C#
Task Start();
```

Not sure how mono is currently integrated into .NET 6 (for Android), there is already one ticket with the same error message: https://github.com/microsoft/vs-streamjsonrpc/issues/387

**Comment by n9** [comment]
@AArnott Could you please release on nuget some preview/testing version with modified "mono" check (that will also include Android):

https://github.com/microsoft/vs-streamjsonrpc/blob/d691f423fcf80be9c85ee802a927be7d852b2480/src/StreamJsonRpc/Utilities.cs#L16

**Comment by n9** [comment]
The "mono" (.net 6 android) issue seems to occur only if the method has no parameters.
Simple example:

```C# 
var type = Type.GetType("System.Object");
//var method = type.GetMethod("ToString");
var method = type.GetMethod("ReferenceEquals");
var parameters = method.GetParameters();
Span<ParameterInfo> ps = parameters.AsSpan(0, 0); // possible exception here
```

Version with `ReferenceEquals` works, but the version with `ToString` fails.

**Comment by AArnott** [comment]
Excellent analysis, @n9. I'm preparing the change now.
