### ISSUE TITLE
Support servers that must be invoked on a captured SynchronizationContext

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-streamjsonrpc#88]
Add a `SynchronizationContext` field to the `JsonRpc` class and all local method invocations will be done by calling `SynchronizationContext.Post`. This `SynchronizationContext` will be either the default one (which schedules work concurrently to the threadpool) or one that is "captured" or otherwise provided in the constructor. That way, folks who want to preserve order of incoming messages can do so by supplying a single-threaded `SynchronizationContext`.

This originally came from #86 but as that was closed as Not Repro, I brought the design idea over here since it is useful for other things too.

**Comment by AArnott** [comment]
@BertanAygun would this be useful to you? Might you construct an STA thread with a Dispatcher before constructing your `JsonRpc` instance so that you could have your server methods invoke on your STA thread directly, thereby eliminating your need to hop to the right thread on each call?
Alternatively, if you would use it this feature but won't have the `SynchronizationContext` ready until after the `JsonRpc` connection is initialized, we could perhaps make this settable after the connection is established via the mechanism we come up with for #62.

**Comment by BertanAygun** [comment]
That would work but the change still needs to guarantee that Post methods are called in order of InvokeAsync calls. From last discussion it sounded like each InvokeAsync was starting its own async work, I assume in this case instead of doing that it will call Post and won't process the next call until Post returns.

**Comment by AArnott** [comment]
On the client side InvokeAsync call, order is already guaranteed. 
On the server-side, with the proposed change, we would call `SynchronizationContext.Post` directly from the read loop, so that order would be preserved on the server side as well, up to the point where we hand it off to the `SynchronizationContext`, which would then be responsible for the order semantics.

If you used the `DispatcherSynchronizationContext`, it would retain order and execute on your UI thread. But if you define async server methods, the execution might interleave between multiple calls, although the initial execution of each async method would be in the proper order.

**Comment by MikhailArkhipov** [comment]
Is 1.4 getting published soon?

**Comment by AArnott** [comment]
It's on nuget.org (as a prerelease package) already. Is that what you need, @MikhailArkhipov ?

**Comment by AArnott** [comment]
1.4 is now a stable package on nuget.org
