### ISSUE TITLE
Add support for JsonPropertyNameAttribute from System.Text.Json

### ISSUE THREAD

**Issue by juaal12** [microsoft/vs-streamjsonrpc#925]
Hi,

Is it planned to add support for System.Text.Json?

I have seen several closed issues regarding this topic (#766 and #305 for example).

In my case I have to use Newtonsoft just to apply a property renaming on my server call. I think we must support System.Text.Json since it is faster, lighter and for sure it will the be standard way for future applications since .NET 6 introduced it.

Thanks in advance!

**Comment by taooceros** [comment]
Hi, when shall 2.16 be released?

**Comment by AArnott** [comment]
@taooceros It was today.

**Comment by juaal12** [comment]
Good morning!

I think the last package release does not solve the support issue. With version `2.16.36 `using `JsonPropertyName `is not behaving like `JsonProperty `provided by Newtonsoft.

```
[JsonProperty("clientId")]
public string ClientId { get; set; }
```

works fine since on generated json `ClientId` will be `clientId`. This is not happening when:

```
[JsonPropertyName("clientId")]
public string ClientId { get; set; }
```

since `ClientId `will still be `ClientId`. 

Using `System.Text.Json` results in having a RemoteException by my side due to this behavior. Should we reopen the issue or should we create a new one?

**Comment by juaal12** [comment]
Hi,

You can notice it does not work fine just upgrading within the test application streamjson package and adding this lines in WebSocketClient `Program.cs`:

```
var stringResult = await jsonRpc.InvokeWithParameterObjectAsync<string>("TestMethod", 
                              new TestDto { TestA = "Client", TestB = "Secret" }, cancellationToken);
```

```
    public class TestDto
    {
        [JsonPropertyName("clientId")]
        public string TestA { get; set; }
        [JsonPropertyName("clientSecret")]
        public string TestB { get; set; }
    }
```

And then these others in JsonRpcServer.cs on in Web project:

```
        public string TestMethod(string clientId, string clientSecret)
        {
            return string.Concat(clientId, clientSecret);
        }
```

**Comment by AArnott** [comment]
I'll take a look.

**Comment by AArnott** [comment]
It's funny, because we have a test that suggests the attribute works:
https://github.com/microsoft/vs-streamjsonrpc/blob/1feb4914a8de326139cf83828dedc4db2bea051e/test/StreamJsonRpc.Tests/SystemTextJsonFormatterTests.cs#L39-L54

(look further down in the file to see use of the attribute).

We also have this test:

https://github.com/microsoft/vs-streamjsonrpc/blob/1feb4914a8de326139cf83828dedc4db2bea051e/test/StreamJsonRpc.Tests/JsonRpcTests.cs#L2906-L2912

Which demonstrates it works for custom named argument objects.

So I tried your repro. It behaves for me. Can you send me a repro project that I can execute?

**Comment by juaal12** [comment]
Sure!

I have forked your `StreamJsonRpc.Sample` repo and I have implemented the modifications in my previous message. Find here the repo: https://github.com/juaal12/StreamJsonRpc.Sample.

Thanks in advance!

**Comment by AArnott** [comment]
Thanks, @juaal12. But your sample doesn't use the formatter for `System.Text.Json` at all. It's using Newtonsoft.Json. That would be why your attributes are being ignored. 
If you want to use the System.Text.Json attributes, change your sample to use `SystemTextJsonFormatter` from this library.

**Comment by juaal12** [comment]
> Thanks, @juaal12. But your sample doesn't use the formatter for `System.Text.Json` at all. It's using Newtonsoft.Json. That would be why your attributes are being ignored. If you want to use the System.Text.Json attributes, change your sample to use `SystemTextJsonFormatter` from this library. [Relevant docs here](https://github.com/microsoft/vs-streamjsonrpc/blob/main/doc/extensibility.md#message-formatters).

Hi @AArnott ,

I have updated the repository with your proposals in the last message. You can take a look if you want but by my side, after applying the changes, it works like a charm, so maybe this is not an issue anymore and we can close the thread.

Nevertheless, if you want to try it, my repo has been updated!

Thanks a lot and sorry for the inconvenience!
