### ISSUE TITLE
How to receive a JSON object as an rpc response?

### ISSUE THREAD

**Issue by newobj** [microsoft/vs-streamjsonrpc#944]
A line of code like 

`var result = await rpc.InvokeAsync<dynamic>("echo", "hi mom");`

yields me

`ArgumentException: Accessed JArray values with invalid key value: "jsonrpc". Int32 array index expected.`

The examples focus on the case of just return an integer, but how do I handle when the server returns an entire object?

The server is written in deno and works fine with other JSON-RPC clients. Its raw response looks like this: 

```
{
    "id": 1,
    "result": {
        "echod": true
    },
    "jsonrpc": "2.0"
}
```

**Comment by AArnott** [comment]
Using `dynamic` as your return type is certainly an interesting idea.
But I'm afraid it isn't supported. We have 3 formatters (Newtonsoft.Json, System.Text.Json, and MessagePack) and each one has a native format for `object` typed deserialization. For example when using `JsonMessageFormatter`, deserializing as `object` (which ultimately is what `dynamic` is, with language syntax sugar) the actual object you'll get back is a `JObject`, which you can downcast to and access everything you need.

I think it would have to be a breaking change to start returning some other type that supports C# dynamic access. We could perhaps put the behavior behind a property on the formatter so you could opt into it. 
I don't see us dedicating the time to add this support in the foreseeable future though.
