### ISSUE TITLE
Parse custom json rpc message responses

### ISSUE THREAD

**Issue by juaal12** [microsoft/vs-streamjsonrpc#947]
I have an JsonRpc server which implements custom response messages, non following the standard response messages. I am having special troubles when it comes to parse a `RemoteInvocationException`. I have read in the documentation that when it comes to a custom error returned from the server, we must create a new class that inherits from `JsonRpc `and override the method `Type GetErrorDetailsDataType(JsonRpcError error)`. 

In my case the server is returning something like:

```
{
  "jsonrpc": "2.0",
  "error": {
    "exceptionClass": "ams.seci.exception.InvalidMachineException",
    "exception": {
      "messageId": "messageId",
      "arguments": [
      ],
      "detailMessage": null,
      "stackTrace": []
    },
    "message": "Message"
  }
}
```

which is a json error response that does not follow the jsonrpc 2.0 standard defined => https://www.jsonrpc.org/specification#error_object

No properties are being mapped to `JsonRpcError `class but `message`. I have dug into the code and message is being mapped because this mapping is being handled by `JsonRpcError `class:

```
        /// <summary>
        /// Gets or sets a short description of the error.
        /// </summary>
        /// <remarks>
        /// The message SHOULD be limited to a concise single sentence.
        /// </remarks>
        [DataMember(Name = "message", Order = 1, IsRequired = true)]
        [STJ.JsonPropertyName("message"), STJ.JsonPropertyOrder(1), STJ.JsonRequired]
        public string? Message { get; set; }
```

I would like to map from my error response the `exceptionClass `json property value because besides the message is the only one that is giving me some useful information. Is there any way for achieving this?

Thanks in advance!

**Comment by AArnott** [comment]
We don't generally support interop with non JSON-RPC compliant remote parties. But you can probably achieve what you want by writing a custom formatter. You *may* even be able to derive from one of our existing JSON formatters. Doing this will give you the chance to derive from the existing JsonRpcError class, to add members, thereby gaining access to them.

But this is just a draft design. I am not certain it will work end to end. Best of luck to you.
