### ISSUE TITLE
Support System.Text.Json compatible Json Converter for Request ID

### ISSUE THREAD

**Issue by snehaavuthu** [microsoft/vs-streamjsonrpc#970]
The RequestIdJsonConverter used to serialize/Deserialize RequestID in JsonRpcRequest and JspnRpcResult object is not compatible with System.Text.Json Serialization. Unable to create our own STJ compatible converter as RequestIdJsonConverter is marked internal. This makes it hard to serialize/deserialize JsonRpcRequest/JsonRpcResult objects using System.Text.Json.Serialization. Is there a way to work around this?

**Comment by snehaavuthu** [comment]
SystemTextJsonFormatter only provides serialization/deserialization of UTF8 encoded JSON. I need a way to serialize/deserialize JsonRpcRequest and JsonRpcResult as a string

**Comment by AArnott** [comment]
That doesn't sound like a scenario we have identified as needing to support up to this point. What are you trying to do? And why is using attributes from a UTF-8 specific JSON serializer important to you if you won't be using the serializer?

**Comment by AArnott** [comment]
Closing due to no response.
