### ISSUE TITLE
Use camelCase for response objects

### ISSUE THREAD

**Issue by nojaf** [microsoft/vs-streamjsonrpc#976]
Hello,

I can't figure out how to return camel case properties from my server.
Right now I have something along the lines of:
```fsharp
type PongResponse = { Message : string }

type MyServer (sender : Stream, reader : Stream) as this =
    let rpc : JsonRpc = JsonRpc.Attach (sender, reader, this)

    interface IDisposable with
        member _.Dispose () = ()

    /// returns a hot task that resolves when the stream has terminated
    member this.WaitForClose = rpc.Completion

    [<JsonRpcMethod("ping", UseSingleObjectParameterDeserialization = true)>]
    member _.Ping (p : PingPayload) : Task<PongResponse> =
        task { return { Message = "And dotnet will answer" } }

let input = Console.OpenStandardInput ()
let output = Console.OpenStandardOutput ()

let daemon =
    new MyServer (Console.OpenStandardOutput (), Console.OpenStandardInput ())

AppDomain.CurrentDomain.ProcessExit.Add (fun _ -> (daemon :> IDisposable).Dispose ())
daemon.WaitForClose.GetAwaiter().GetResult ()
exit 0
```

I invoke this from Node.JS and I get back `{ "Message": "And dotnet will answer" }`.
What am I missing to have `"message"` instead?

**Comment by AArnott** [comment]
Is there any reason you don't do this?

```diff
-        task { return { Message = "And dotnet will answer" } }
+        task { return { message = "And dotnet will answer" } }
```

**Comment by nojaf** [comment]
Properties in dotnet aren't typically lowercase. So, it is a bit of a habit I suppose.
If the easy answer is just to write lowercase properties, then that is a sufficient answer for me.
I just assumed it might be configurable somehow.

**Comment by AArnott** [comment]
It _is_ configurable. But not at the StreamJsonRpc level. You'd have to tell your serializer of choice (Newtonsoft.Json in this case) that you want to do it. StreamJsonRpc [exposes the APIs necessary for you to do this](https://github.com/microsoft/vs-streamjsonrpc/blob/main/doc/extensibility.md#choosing-your-formatter). You'll have to instantiate a `JsonMessageFormatter` yourself, then use its properties to set the Newtonsoft.Json settings to automatically change the naming convention. Then use that formatter in a handler that you then pass to the JsonRpc you create. So your one `JsonRpc.Attach` line of code will become 3-5 lines. But then, all the property names will adjust automatically.

**Comment by nojaf** [comment]
Thanks, I got it working:

```fsharp
    let jsonMessageFormatter = new JsonMessageFormatter ()
    do jsonMessageFormatter.JsonSerializer.ContractResolver <- DefaultContractResolver(NamingStrategy = CamelCaseNamingStrategy())
    let handler = new HeaderDelimitedMessageHandler (sender, reader, jsonMessageFormatter)
    let rpc : JsonRpc = new JsonRpc(handler, this)
    do rpc.StartListening()
```
