### ISSUE TITLE
Intercept a request and modify it before sending to the server

### ISSUE THREAD

**Issue by Rishabh-V** [microsoft/vs-streamjsonrpc#978]
Hi folks,

I am writing a language server client for Visual Studio in C# implementing `ILanguageClient` and `ILanguageClientCustomMessage2`. The language server is not owned/managed by us. When the client sends the initialize request, Client Capabilities is sent to the server. One of the values that is sent is for `TextDocument.PublishDiagnostics.TagSupport`. The built-in client sends the value as 
```
Capabilities.TextDocument.PublishDiagnostics.TagSupport = new TagSupport
{
	ValueSet = new DiagnosticTag[4]
	{
		DiagnosticTag.Unnecessary,
		DiagnosticTag.Deprecated,
		(DiagnosticTag)(-1),
		(DiagnosticTag)(-2)
	}
};
```
Of this the values -1 and -2 causes the server activation to fail as these  values results in parser error in the language server.

Since I cannot get the language server to change, I am trying to intercept the initialize request and change the TagSupport value so that language server can start without any issues. However, I noticed that even after implementing the `ILanguageClientMiddleLayer` and assigning it to `MiddleLayer` property of my client, it doesn't intercept the Initialize request. 

If there is a code sample or documentation or pointer to intercept and modify the initialize request from the client, it would be great.

PS: Please excuse me if this is not the forum to log this issue. Thanks.

**Comment by AArnott** [comment]
This seems more like an LSP-specific request. StreamJsonRpc doesn't provide for adding any middleware layer to modify an outbound requests. I'll see if any of the LSP folks can jump in here or recommend an alternate forum for your question.

**Comment by matteo-prosperi** [comment]
Implementing the [ILanguageClientMiddleLayer](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.languageserver.client.ilanguageclientmiddlelayer) interface should allow you to intercept the `initialize` message and modify it in a way that is acceptable to the server.

**Comment by matteo-prosperi** [comment]
> However, I noticed that even after implementing the ILanguageClientMiddleLayer and assigning it to MiddleLayer property of my client, it doesn't intercept the Initialize request.

Are you getting calls to the `ILanguageClientMiddleLayer.CanHandle` method? Are you returning true from it for the messages you want to modify?
How early are you assigning the middle layer to the `ILanguageClientCustomMessage2.MiddleLayer` property? I would suggest doing it at construction time.

**Comment by davidwengier** [comment]
If I'm reading the code correctly, I don't think the initialize request is interceptable in the middle layer

initialize is dispatched [here](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=/src/product/RemoteLanguage/Impl/LegacyInfrastructure/RemoteLanguageServiceBroker.Adapter.cs&version=GBdevelop&line=681&lineEnd=682&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) but the middle layer only comes into play a few lines later in that method, [here](https://devdiv.visualstudio.com/DevDiv/_git/VSLanguageServerClient?path=/src/product/RemoteLanguage/Impl/LegacyInfrastructure/RemoteLanguageServiceBroker.Adapter.cs&version=GBdevelop&line=719&lineEnd=720&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

I think the solution here might be to create a language server that gets all of the requests, and then in turn delegates them to the underlying server you don't own.

**Comment by Rishabh-V** [comment]
Thanks @AArnott, @matteo-prosperi, @davidwengier for pitching in and helping.

@matteo-prosperi -  I am returning `true` from `CanHandle` method but `CanHandle` is fired for textdocument/didOpen at the start when the file is opened but not for the InitializeRequest and so unable to intercept this request. `OnServerInitializeFailedAsync` is called directly.

@davidwengier - This was my assessment as well while debugging the source. The `RemoteLanguageClientInstance` has a method named `SendInitializeRequestAsync` which is responsible for sending the InitializeRequest. I modified the `InitializeParams` to remove the PublishDiagnostics value while debugging and post that all the requests were intercepted by the middle layer.

Couple of questions on the suggestion approach:
1) Will there be any foreseeable delay in this approach, for example in intellisense or hover?
2) Is there a sample or reference code I can refer to get this right the first time? 

Many thanks to all of you!

**Comment by davidwengier** [comment]
1. There will be delays, though whether they impact the user is questionable. Doing things this way means two different duplex streams, and therefore any serialization/deserialization overhead is doubled, as your delegating server necessarily has to deserialize everything, only to reserialize it again. I will say though that we use this system in VS for the Razor editor, and the Html editor when its LSP mode is turned on. In fact, in the Razor editor we often delegate to the Html server, which in turn delegates to the CSS or TypeScript server, so we're already doing this, and doing it in a more convoluted way than you will.
2. Not sure there is a great example of this, but the code for the Razor server is OSS. It's a bit convoluted as it uses a library provided by Roslyn for its server, and it doesn't delegate directly to any other servers, but rather goes back through VS buffers to do it, which is probably overkill for your needs. If you want to start digging in though, our ILanguageClient implementation is here: https://github.com/dotnet/razor/blob/main/src/Razor/src/Microsoft.VisualStudio.LanguageServerClient.Razor/RazorLanguageServerClient.cs

**Comment by Rishabh-V** [comment]
Thanks @davidwengier for sharing the details. Appreciate your help. I will give it a try. 

I do hope though that given such issues, there should be a way to change the Client Capabilities in the client somewhere. 

Thanks again everyone and I am happy to close this issue.
