### ISSUE TITLE
Add Headers support for WebSocketMessageHandler

### ISSUE THREAD

**Issue by yingfangdu** [Microsoft/vs-streamjsonrpc#98]
I am using vscode-ws-jsonrpc from client side and using vs-streamjsonrpc from server side. The communication is through WebSocket.

While vscode-ws-jsonrpc always expect headers in the message (sending and receiving)

Could you please abstract the Headers feature from HeaderDelimitedMessageHandler and make it to be configurable for these message handlers so that we can enable /disable as needed for different jsonrpc libs?

**Comment by AArnott** [comment]
That seems reasonable.
But I wonder: why does vscode-ws-jsonrpc use headers? Web sockets provide message boundaries in the transport, so I found that the headers were not necessary.

**Comment by yingfangdu** [comment]
I think the solution is to let vs-jsonrpc to remove the headers as the header is not necessary at all.
Adding a header does not follow the jsonrpc protocol.

While for StreamJsonRPC, in order to work with other library, I think the header should be configurable.

**Comment by AArnott** [comment]
You can do this today by exposing your WebSocket as a stream and then using the `HeaderDelimitedMessageHandler` class (which is used by default for streams). `WebSocket` doesn't offer an `AsStream()` extension method, unfortunately. But it's not too hard to write such a wrapper class. My team has an implementation of this that is ~150 lines.

If #80 is fixed, that may allow us to offer `HeaderDelimitedMessageHandler` for `WebSocket` as well.
