### ISSUE TITLE
package downgrade caused by v2.17.8

### ISSUE THREAD

**Issue by baywet** [microsoft/vs-streamjsonrpc#980]
Hi everyone,
Upgrading to 2.17.8 causes package downgrade warnings.
See [this example](https://github.com/microsoft/kiota/pull/3719).

I believe merging #967 and #965 should fix this.

**Comment by AArnott** [comment]
Whoa. I didn't think we'd be possible of introducing package downgrade warnings at this level, but it appears you're right. Thanks for reporting.

**Comment by AArnott** [comment]
In the meantime, you can always workaround it by adding a PackageReference to the newer versioned package directly to your project file.

**Comment by baywet** [comment]
in our case we're not in a rush to get the newer version, we'll just wait for the next one. I was simply reporting this so the problem gets addressed.

**Comment by AArnott** [comment]
I think this is the crux of the issue, actually. It comes from your build log:

> error NU1603: Warning As Error: StreamJsonRpc 2.17.8 depends on Microsoft.VisualStudio.Threading (>= 17.7.35) but Microsoft.VisualStudio.Threading 17.7.35 was not found. An approximate best match of Microsoft.VisualStudio.Threading 17.8.14 was resolved. 

It seems a version of Microsoft.VisualStudio.Threading is missing from nuget.org. Pushing _that_ version will probably fix your build.

**Comment by AArnott** [comment]
Apparently we tried to push that missing package yesterday, but nuget.org rejected it. We're pursuing mitigations.

**Comment by AArnott** [comment]
This should be resolved. Can you please confirm, @baywet?

**Comment by baywet** [comment]
Yes it now works. Thanks for the help. Closing.
